### ISSUE TITLE
Large size even after webpack bundle

### ISSUE THREAD

**Issue by vpanichkin** [pdfme/pdfme#101]
Hi, dear contributors.

I found your PDF generation tool very useful. However, even after bundling with webpack it contains ~3MB of code. Is there any way to have a lightweight version in the future?

<img width="755" alt="image" src="https://user-images.githubusercontent.com/16993030/197564947-ed9e54d6-4fa4-4c6d-b127-718339173772.png">

**Comment by hand-dot** [comment]
Hi @vpanichkin 
Thank you for reporting the issue.

Now we can't support tree shaking, but I'll support it.

**Comment by vpanichkin** [comment]
Thanks for the fast response. In fact, tree shaking would be an amazing add-on :) Is there some timeline or priority for this feature?

**Comment by hand-dot** [comment]
@vpanichkin 
Now we don't have a timeline or priority for this feature...
If you have an idea to implement this. Please share with me.

**Comment by hand-dot** [comment]
I don't know how to create tree shakeable lib...

but, bellow document is very useful. 
Ref: https://webpack.js.org/guides/tree-shaking/

if somebody who can  support tree shake, please comment on this issue...

**Comment by hand-dot** [comment]
Usefull Link: 
- https://blog.theodo.com/2021/04/library-tree-shaking/
- https://zenn.dev/nissy_dev/articles/how-to-make-tree-shakeable-libraries

**Comment by hand-dot** [comment]
Maybe, we should use Vite's library mode....
https://vitejs.dev/guide/build.html#library-mode

**Comment by vpanichkin** [comment]
Great work. Thanks for finishing it :)
