### ISSUE TITLE
How to add new schemas?

### ISSUE THREAD

**Issue by psociety** [pdfme/pdfme#103]
Thank you for creating PDFMe! It's really cool!

How can i add new schemas?
Seems like the only way is downloading the sources and violating them. Is that the official way?

**Comment by hand-dot** [comment]
Do you mean new type schemas?

> Seems like the only way is downloading the sources and violating them. Is that the official way?
If so, the above way is right.

**Comment by psociety** [comment]
> Do you mean new type schemas?

Yes. Ok, will do it that way then!

By the way:
https://github.com/pdfme/pdfme/blob/f8113fb97817352aa22586193f9286790786c1b1/packages/ui/src/components/Designer/index.tsx#L121
timeTavel lol xD
