### ISSUE TITLE
Custom Label for UI

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#107]
ref: https://github.com/pdfme/pdfme/pull/323

---

Currently, changing the language settings translates some labels, but eventually, the aim is to make all labels translatable, and additionally add a setting to overwrite specific keys.

- [x] Remove unused labels from i18n.ts as well.
- [x] Make i18n overwritable from options
- [x] Retrieve existing schema labels from the labels in options
- [x] Add a tips to the documentation for overriding the official schema labels
- [x] Release
  - [x]  npm
  - [x]  website
  - [x]  playground

`options.labels`

---

ref https://github.com/pdfme/pdfme/discussions/98
ref https://github.com/pdfme/pdfme/pull/100
ref https://github.com/pdfme/pdfme/issues/265

**Comment by MarioWork** [comment]
maybe this note can be removed from docs 
https://pdfme.com/docs/custom-ui
<img width="768" height="104" alt="Image" src="https://github.com/user-attachments/assets/6763416c-1e32-45c1-846f-a37ae31f8c79" />
