### ISSUE TITLE
Support set properties for PDF document.

### ISSUE THREAD

**Issue by kymap057** [pdfme/pdfme#108]
Hi, the library is very impressive!

I think that you should add on the Customize feature to set title, author, subject for document properties when generate pdf file.
you can use methods in pdf-lib library, you can do it!
refer: https://pdf-lib.js.org/docs/api/classes/pdfdocument#methods

Thank you!

**Comment by hand-dot** [comment]
Add properties and meta options to the generator to make it possible.
