### ISSUE TITLE
ERROR Unhandled Promise Rejection

### ISSUE THREAD

**Issue by lucasoliveira08** [pdfme/pdfme#109]
Hi!

When I run the lambda in my machine, through the _serverless invoke local --function generate --path event_mock.json_ command, it generates correctly. when it is through the endpoint, the following error occurs: 

`{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Invalid argument:\n--------------------------\nERROR POSITION: inputs.0.name\nERROR MESSAGE: Required\n--------------------------",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Invalid argument:\n--------------------------\nERROR POSITION: inputs.0.name\nERROR MESSAGE: Required\n--------------------------",
        "stack": [
            "Error: Invalid argument:",
            "--------------------------",
            "ERROR POSITION: inputs.0.name",
            "ERROR MESSAGE: Required",
            "--------------------------",
            "    at Je (/var/task/node_modules/@pdfme/generator/dist/index.js:2:2194500)",
            "    at _e (/var/task/node_modules/@pdfme/generator/dist/index.js:2:2194745)",
            "    at /var/task/node_modules/@pdfme/generator/dist/index.js:2:3159977",
            "    at Generator.next (<anonymous>)",
            "    at /var/task/node_modules/@pdfme/generator/dist/index.js:2:3159891",
            "    at new Promise (<anonymous>)",
            "    at vQ (/var/task/node_modules/@pdfme/generator/dist/index.js:2:3159636)",
            "    at wQ (/var/task/node_modules/@pdfme/generator/dist/index.js:2:3159915)",
            "    at /var/task/handlers/GeneratePdfHandler.js:171:38",
            "    at new Promise (<anonymous>)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Invalid argument:",
        "--------------------------",
        "ERROR POSITION: inputs.0.name",
        "ERROR MESSAGE: Required",
        "--------------------------",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}`

It's the same json in the req body and the event_mock.json...
Any idea?

**Comment by hand-dot** [comment]
Hi @lucasoliveira08 
Can you share the input data?
Maybe, Your input data is not correct...

**Comment by lucasoliveira08** [comment]
Yes, after long hours trying I found that only one json.parse was missing HAHAHAHAHA

It's part of the process...

Btw, thank's for the answer

**Comment by hand-dot** [comment]
Okay! Good luck!
