### ISSUE TITLE
Support adding new pages to template

### ISSUE THREAD

**Issue by asanoviskhak** [pdfme/pdfme#111]
Hi there! I love what you are doing. I was playing around your library and found out that you can't add new page dynamically in editing modes. It would be great to have that, thanks!

**Comment by asanoviskhak** [comment]
Mainly it would be creating PDF from blank, and not importing BASE_PDF, or build on top of BASE_PDF

**Comment by hand-dot** [comment]
Hi! Thank you for the feature suggestion👍

Could you please tell me more detail and user interface and function interface?

**Comment by hand-dot** [comment]
@asanoviskhak 

I labeled the answer because I did not receive a reply.
If there are no replies at this point, it will be closed after 30 days.
If you have any questions, please comment.

**Comment by halindraprakoso** [comment]
I'm probably has the same idea. Basically, afaik there's no option to start from blank in the template designer on the website as users are currently required to make and use a blank pdf as the basePDF

**Comment by xips1337** [comment]
Поддерживаю идею!

**Comment by ujjwal-neu** [comment]
any updates on this feature or a way around to achieve this?

**Comment by sushi2all** [comment]
The idea could simply be to have a "Add a blank page" section, with a height and width definition and then regenerate the template base pdf.

See relevant `pdf-lib` [docs](https://pdf-lib.js.org/docs/api/classes/pdfdocument#addpage)

**Comment by Ben-CA** [comment]
Would also like to see multi-page support.

**Comment by peteward** [comment]
> Would also like to see multi-page support.

pdfme is does support multiple pages, just not dynamically creating them for an existing base template/pdf.

This shouldn't be too hard to implement if someone is willing to contribute.

**Comment by urenpatelce** [comment]
@peteward as you mentioned that pdfme supports multiple pages, so then what will be the template schema? is it possible to have the multiple pages designing at the same time ?

**Comment by hand-dot** [comment]
implemented by https://github.com/pdfme/pdfme/pull/394

**Comment by mohameddev19** [comment]
> implemented by [#394](https://github.com/pdfme/pdfme/pull/394)

First and foremost, I wish to commend your tremendous efforts and extend my deepest gratitude for them, and I truly regret that I was unable to assist.
Following the library installation, the 'Add New Page' button is absent from the Designer, although it is visible and functional in the Playground.
