### ISSUE TITLE
How to add variable length data?

### ISSUE THREAD

**Issue by gregfenton** [pdfme/pdfme#119]
Is there any way to create, for example, a table with a variable number of rows?  I would like to pass in data coming from user input or from a database and I do not know the number of rows ahead of time.  Could be dozens or hundreds.

Are there any examples or codesandboxes that demonstrate such a thing?

**Comment by hand-dot** [comment]
We can't create a dynamic table now.
But you can create a template dynamically so that you can achieve it technically.


ref [Add border properties to the schema #30](https://github.com/pdfme/pdfme/issues/30)

**Comment by Hibrix-net** [comment]
Hello,

Is there any way one can generate dynamic data PDFs like what you're doing in the labels from here? https://github.com/pdfme/pdfme/blob/main/website/static/templates/address_label_10.json

I mean to be able to have a dynamic schema for filling up e.g. products and generate a product catalogue in a way that every page is filling up with each product and start a new page when it's full. Each product will share the same schemas and each page can contain a different amount of let's say "product cards" depending on the length of each product content.

Something like:
1. Image1, Product Name1, Product Price1
2. Image2, Product Name2, Product Price2
3. Image3, Product Name3, Product Price3
 ... and so on until the end of the page, then a new page... etc.

But the event.data + dynamic schema approach filling it up the pages of the PDF.

Best regards,

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/discussions/148
