### ISSUE TITLE
RGB->CMYK option

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#134]
Some users want to use CMYK color(especially DTP designers).

But now, we can use RGB only.
It should be able to use by option.

---

https://pdf-lib.js.org/docs/api/interfaces/cmyk

**Comment by messisawesome10** [comment]
I  would like to use opacity in my colors, would this be possible to add?

**Comment by hand-dot** [comment]
Implemented by https://github.com/pdfme/pdfme/pull/436
