### ISSUE TITLE
Add Datamatrix (and others) to code generation options

### ISSUE THREAD

**Issue by sushi2all** [pdfme/pdfme#136]
### Is your feature request related to a problem? Please describe.

Many manufacturing companies use [Data Matrix](https://en.wikipedia.org/wiki/Data_Matrix) for 2D codes, but it's not currently available in the Template Designer options.

### Describe the solution you'd like

I know `bwip-js`, on which `pdfme` is based, can output Data Matrixes and also many more types than the ones available in the Template Designer. It would be great to include Data Matrix and, in general, why not include all the options of `bwip-js`?

### Describe alternatives you've considered

None. I've used `bwip-js` directly for this purpose.

### Additional context

PDF generation can be very useful in manufacturing contexts to produce reports and worksheets. Maintaining consistency across different uses of 2D codes can greatly increase the user experience of operators in general.

**Comment by Yan-Anq** [comment]
Hi @sushi2all,

I've the same problem, and for waiting this new feature, I'm using this code :

```js
import { BLANK_PDF, generate } from '@pdfme/generator'
import bwipjs from 'bwip-js'

let bufDatamatrix = bwipjs.toCanvas({
  bcid:        type,
  text:        contenu,
  scale:       5,
  height:     50,
  width:       50,
  textxalign:  'center',
}, document.createElement('canvas'))

contenu = bufDatamatrix.toDataURL('image/png') // <------ get the Base64 content

const template = {
  "schemas": [
    {
      "field1": {
        "type": "image", // <----- image for the datamatrix
        "position": {
          "x": 24.87,
          "y": 91.55
        },
        "width": 35,
        "height": 7
      }
    }
  ],
  "basePdf": BLANK_PDF
}

const inputs = [
  {
    "field1": contenu // <----- content in Base 64
  }
]

await generate({ template, inputs}).then((pdf) => {
  console.log(`Génération du PDF : OK.`)
  const blob = new Blob([pdf.buffer], { type: 'application/pdf' })
  window.open(URL.createObjectURL(blob))
}

```

Maybe we can get the 'bwipjs' instance from '@pdfme/generator' instance, but I don't know how to do this.

Hope this help.
Yan

**Comment by hand-dot** [comment]
Hi @sushi2all !
Thank you for the feature request.
pdfme is an Open source project, you can add the Datamatrix barcode type by yourself.
(I suggest you searching 'japanpost', you can find how to add new barcode type )

I welcome your pull request.

**Comment by hand-dot** [comment]
@sushi2all 
Can you add Datamatrix barcode  as new barcodes schemas.

https://github.com/pdfme/pdfme/tree/main/packages/schemas/src/barcodes

**Comment by hand-dot** [comment]
Since the plugin mechanism allows for self-creation, there's no need to create this as an issue. 

Alternatively, please create a PR. I'll close this.
