### ISSUE TITLE
 Error: Unknown font format

### ISSUE THREAD

**Issue by Roisfaozi** [pdfme/pdfme#141]
### Describe the bug

I got error when try to download generated PDF with custom font function.

Same issues when I run pdfme playground repository in my local development.

### To Reproduce

 const onGeneratePDF = async () => {
    if (designer.current) {
      const template = designer.current.getTemplate();
      const inputs = template.sampledata ?? [];
      const font = await getFontsData();
      const pdf = await generate({ template, inputs, options: { font } }).then((pdf) => {
        const blob = new Blob([pdf.buffer], { type: 'application/pdf' });
        window.open(URL.createObjectURL(blob));
      });
      // const blob = new Blob([pdf.buffer], { type: "application/pdf" })
      // window.open(URL.createObjectURL(blob))
    }
  };

### Expected behavior

I can generate PDF with custom font and downloaded

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/generator
- pdfme version:1.1.5
- Operating system: Windows 10 64 bit
- Node.js version or Browser name & version: Chrome 109.0.5414.120 (Official Build) (64-bit)
```

### Your Error Log

```shell
Uncaught (in promise) Error: Unknown font format
    at Object.create (fontkit.es.js:17839:1)
    at Function.<anonymous> (CustomFontSubsetEmbedder.ts:19:1)
    at step (tslib.es6.js:100:1)
    at Object.next (tslib.es6.js:81:1)
    at tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:70:1)
    at CustomFontSubsetEmbedder.for (CustomFontSubsetEmbedder.ts:13:1)
    at PDFDocument.<anonymous> (PDFDocument.ts:954:1)
    at step (tslib.es6.js:100:1)
```

**Comment by Yan-Anq** [comment]
Hi @Roisfaozi,
Maybe your function 'getFontsData()' return a bad format ? Do you have the code for this one?

Have you seen this link about font integration  :
[](https://pdfme.com/docs/guides/custom-font )

For me I had a problem because I had used two time the 'fallback' option. So it's ok now because I have only one option with 'fallback: true', and the others are 'fallback: false'.

Yan
