### ISSUE TITLE
Rotate problem on multiline text

### ISSUE THREAD

**Issue by Yan-Anq** [pdfme/pdfme#142]
### Describe the bug

When I rotate a text with multines (for example 90 deg), I obtain an unique line :
![rotate_wish](https://user-images.githubusercontent.com/124576871/216959325-1f183de5-c95b-4b9a-801b-3e529ca946ed.png)

### To Reproduce

I use 'rotate' parameter :

```js
const template = {
  "schemas": [
    {
      "field1": {
        "type": "text",
        "position": {
          "x": 24.87,
          "y": 91.55
        },
        "width": 250,
        "height": 100,
        "alignment": "left",
        "fontSize": 10,
        "characterSpacing": 0,
        "lineHeight": 1,
        "rotate": 90    // <------ Rotation 90deg
      }
    }
  ],
  "basePdf": BLANK_PDF
};
```

### Expected behavior

Each lines must be separate with a 'lineHeight' parameter.

### Your Environment

```markdown
- pdfme package : @pdfme/generator
- pdfme version: ^1.1.5
- Operating system: Docker Windows Desktop (VueJs 3 + Vite)
```

### Your Error Log

```shell
No error in console.
```

**Comment by hand-dot** [comment]
Reproduce by Sample App: https://stackblitz.com/edit/typescript-efv8uk?file=index.ts
