### ISSUE TITLE
Error with HELVETICA import/export when updating version above 1.1.7

### ISSUE THREAD

**Issue by steffancarrington** [pdfme/pdfme#149]
### Describe the bug

When updating the PDFME packages to anything above version 1.1.7 we are getting an issue with missing HELVETICA import/export from @pdfme/common package. 

Is this a known issue? 

### To Reproduce

Update both `pdfme/ui` and `pdfme/generator` packages to v.1.1.7 or later.

### Expected behavior

To be able to update to the latest package version without encountering missing import/export errors.

### Your Environment

```markdown
- @pdfme/ui & @pdfme/generator
- pdfme version: 1.1.9
- Operating system: MacOS Ventura 13.2.1
- Node.js version or Browser name & version: Node v.16.18.1, ReactJS & TypeScript
```

### Your Error Log

```shell
./node_modules/@pdfme/generator/dist/esm/src/index.js
Attempted import error: 'HELVETICA' is not exported from '@pdfme/common'.
```

**Comment by hand-dot** [comment]
Hi @steffancarrington 

Thank you report the bug. I'll check this problem when I have time.
If you find a cause, please let me know.

Thanks

**Comment by steffancarrington** [comment]
Hey @hand-dot , 

Thanks for the response, I'm currently looking into it from my side just to confirm it's not an issue with my setup. 👍
