### ISSUE TITLE
Linebreaks cut off characters

### ISSUE THREAD

**Issue by Jactami** [pdfme/pdfme#152]
### Describe the bug

When I create a multi-line text block, linebreaks sometimes cut off the last character and cause overlapping characters in the next line.

Example: In this case the word _"In"_ is split causing the _"n"_ to move to the following line and overlap the next word.

<img width="680" alt="pdfme_bug" src="https://user-images.githubusercontent.com/53863684/228532641-bf36579e-8fd0-4e60-83d3-cccfe1464ef4.png">

### To Reproduce

The bug can be reproduced by the following code snippet. I also provide a quick live demo:
- [Codesandbox](https://codesandbox.io/p/sandbox/quiet-voice-0qqnk1?file=%2Fsrc%2Fcomponents%2FPdf.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A55%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A55%7D%5D)
- [Fullscreen Demo](https://0qqnk1-3000.csb.app/)

_(Note that I use an Open Sans font, but the problem also occured throughout my pdf with the default Helvetica font.)_

```ts
const template = {
  basePdf: BLANK_PDF,
  schemas: [
    {
      methodologyChapter: {
        type: 'text',
        position: {
          x: 25,
          y: 20,
        },
        width: 165,
        height: 10,
        fontSize: 18,
        fontColor: '#96ca50',
        fontName: 'openSans',
        alignment: 'left',
        lineHeight: 1,
        backgroundColor: '#FFF',
      },
      methodologyDesc: {
        type: 'text',
        position: {
          x: 25,
          y: 30,
        },
        width: 165,
        height: 60,
        fontSize: 11,
        fontColor: '#000',
        fontName: 'openSans',
        alignment: 'left',
        lineHeight: 1.5,
        backgroundColor: '#FFF',
      },
    },
  ],
};

const inputs = [
  {
    methodologyChapter: 'METHODIK',
    methodologyDesc:
      'Unsere Methodik basiert auf den Erkenntnissen der 15-Minuten-Stadt. Ein Viertel der kurzen Wege ist das Ziel nachhaltiger Stadtentwicklung. Die 15-Minuten-Stadt dient als Vision den Menschen und seinen Lebensalltag in den Mittelpunkt zu stellen. Das neue Stadtmodell ist in aller Munde, das Konzept dahinter als „Stadt der kurzen Wege“ schon lange Ziel nachhaltiger Stadtentwicklung und das Fahrrad ist einer der Hauptverkehrsträger im Konzept. Die 15-Minuten-Stadt ist ein aktuell viel beachtetes städtebauliches Leitbild. Sie dient als Vision, um bei der Planung wieder den Menschen und seinen Lebensalltag in den Mittelpunkt zu stellen. In der modernen und lebenswerten Stadt ist alles auch ohne Auto gut erreichbar.',
  },
];

const fonts = {
  openSans: {
    data: await fetch('fonts/open-sans-v18-latin-300.woff').then((res) => res.arrayBuffer()),
    fallback: true,
  },
};

const pdf = await generate({ template, inputs, options: { font: fonts } });
```

### Expected behavior

Linebreaks should always take place between words. A word schould never be split into two parts.

### Your Environment

```markdown
- pdfme package: @pdfme/generator
- pdfme version: ^1.1.9
- Operating system: MacOS and Windows
- Node.js version or Browser name & version: Node v18.15.0 + Electron + Vuejs 3 + Vite
```

### Your Error Log

```shell
No errors in console.
```

### Additional context

_No additional context._

**Comment by hand-dot** [comment]
Hi @Jactami 


Thank you very much for your kind attention to the reproduction code.
I was able to confirm the problem.

Perhaps there is a problem with the [drawInputByTextSchema](https://github.com/pdfme/pdfme/blob/c1fad54d07740b4f77b59382f87ec9c17640e2e5/packages/generator/src/helper.ts#L274) function...

**Comment by hand-dot** [comment]
duplicate: https://github.com/pdfme/pdfme/issues/174

I'll handle this issue in https://github.com/pdfme/pdfme/issues/174
