### ISSUE TITLE
Maintain a changelog to make upgrading easier

### ISSUE THREAD

**Issue by jameshalsall** [pdfme/pdfme#154]
### Is your feature request related to a problem? Please describe.

When upgrading pdfme in a downstream project it is important that a changelog is available to understand the impact of the changes in pdfme. This will help determine what testing is required in the downstream project as well. Additionally, it helps understand if a bug has already been fixed.

The commits don't really help here either, as we can see below it's impossible to tell what changed between version 1.1.7 and 1.1.9:

![Screenshot 2023-03-30 at 08 57 53](https://user-images.githubusercontent.com/499932/228769255-b22d414b-8ef0-4e6a-8b4f-9c50593dffcb.png)

### Describe the solution you'd like

A published changelog available with information about what has changed. This could be manually curated or, easier and better I think, using the [automated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) in GitHub releases. This will mean having to funnel all changes through PRs because the release notes are generated based on the PRs and not the commits.

### Describe alternatives you've considered

n/a

**Comment by hand-dot** [comment]
You are right.
Sorry for my bad release.

I'll change the release operation.
and consider using Automatically generated release notes.

Thank you for your advice.

**Comment by jameshalsall** [comment]
thanks @hand-dot - I appreciate you're really busy, thanks for the great work on pdfme 👍🏻

**Comment by sandrooco** [comment]
@hand-dot Thanks for pulling through and updating many things in the last few versions. It's great.
Any chance we could get some changelogs for V6+? Upgrading worked for me but I fear that I might miss some implications that might brick my stuff, thus I'm not yet confident to go to prod with the upgrade.
