### ISSUE TITLE
Cannot select text fields on pdf when moving between pages

### ISSUE THREAD

**Issue by justus-lattice** [pdfme/pdfme#156]
### Describe the bug

When working with a pdf with multiple pages, if you leave a page and come back, you are no longer able to select the field on the page.

### To Reproduce

- Upload 2 page pdf here: https://pdfme.com/template-design
- Add a field
- Scroll to page 2, without clicking anything
- Scroll back to page 1, without clicking anything
- You cannot click on any of the fields (*Note*: you are able to perform a workaround by clicking on an empty part of the pdf first, and then click on the field)

### Expected behavior

Field should continue to remain clickable even when scrolling through multiple pages.

### Your Environment

```markdown
- https://pdfme.com/template-design
- Operating system: Mac 12.6.3
- Node.js version or Browser name & version: Chrome 111.0.5563.146
```

### Your Error Log

```shell
N/A
```

**Comment by hand-dot** [comment]
Hi @justus-lattice !

Thank you for reporting the bug.

I understood the problem you identified.
Sorry, but I do not have enough time to fix this problem.

If you submit a PR, I’ll check ASAP.

**Comment by hand-dot** [comment]
Fixed by latest version.
![CleanShot 2023-08-20 at 13 28 39](https://github.com/pdfme/pdfme/assets/24843808/7c29ff8f-d29a-4544-b5ad-ad3a30e9356a)
