### ISSUE TITLE
Add prefix and suffix to text fields

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#159]
### Is your feature request related to a problem? Please describe.

We sometimes want a text field to include some static content. An example below shows the dynamic component of someone's name, rendered with a "Hi " prefix and "!" suffix:
![Screenshot 2023-04-14 at 10 48 43](https://user-images.githubusercontent.com/7068515/232010752-e0586ed6-f152-42f0-91b8-775706d3b89c.png)

They are all part of the same text content, but there is a static part of the data that should be entered as part of the design.

### Describe the solution you'd like

The UX for this is quite challenging, and I'm still exploring how this could work.

The simplest approach would be to have `prefix` and `suffix` textareas as part of the field definition. The complexity comes with the ability to edit content on the field, as you might be editing the prefix or suffix instead of the example input. 

### Describe alternatives you've considered

The alternative/workaround would be to append the static content to the dynamic when it's passed the renderer. However, this is confusing concerns as the designer should ideally capture design-related issues and it should be represented in the schema. 

### Additional context

I will continue the research on this today and present some ideas soon.

**Comment by peteward** [comment]
This is definitely challenging from a UX perspective!

The best, or at least easiest and least disruptive to how things currently works that we can think of is having the 2 additional text boxes and indicate which part of the text is prefix / suffix by a background highlight (although this might be challenging technically): 

![Screenshot 2023-04-14 at 14 08 43](https://user-images.githubusercontent.com/7068515/232053831-06e3ce8d-02fd-43c4-a56f-b43792edf225.png)

In order to add a prefix and / or suffix you would have to enter the text from the text-boxes on the right side initially. The in-line representation would have to build it's content from concatenating the 3 boxes and highlighting the prefix and suffix.  Once they exist you could edit them inline and would update the box corresponding to where you are within the text.

There are some edge cases, such as deleting the prefix or suffix entirely would mean they could only be re-added from the right-hand side. Also when editing on the character between sections you have the confusion of which part you are amending. 

It's not perfect :/

**Comment by hand-dot** [comment]
Hi @peteward 

I think we can use a template engine or similar to process the strings before passing inputs to the generator.

Personally, I feel this is a lot of overhead to deal with in pdfme.

**Comment by peteward** [comment]
Yeah, another tool I am looking to replace allows text boxes where you can toggle between source and preview mode and they contain the variable:

```
Hi %name%!!!
```

But I didn't think this really fits with the architecture of pdfme. I thought the prefix and suffix idea was less intrusive to how things work currently.

**Comment by peteward** [comment]
Closing in favour of #201
