### ISSUE TITLE
Click behaviour on text fields in Designer UI

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#160]
### Is your feature request related to a problem? Please describe.

Currently, it feels a bit confusing when you click on a text field. I expected to double-click to edit which toggles you back out of edit mode. 

Also, if you click once to enter a text field it puts the cursor at the end of the content. I wanted to change content in the middle of the string so I clicked the mouse in the middle like I would a normal text box and it's now no longer in edit mode. I click again and the cursor is back at the end of the string.

### Describe the solution you'd like

I think it might be less confusing if double-click was used to enter/exit the edit mode on a field. 
This way you could use the mouse to position the cursor on the field.

Maybe it's just me though! :) 

### Describe alternatives you've considered

Keep it unchanged if other people think it's ok

**Comment by peteward** [comment]
Perhaps the issue is not needing a double-click to enable editing, but that when you click inside the box you are already editing it shouldn't cancel edit mode? This would give you normal cursor control to click a position within the text box, and also drag-select text to cut/copy/delete

**Comment by hand-dot** [comment]
Hi @peteward 

Thanks for suggesting the issue.
Yes, I would like to hear what others have to say.

The current behavior is as follows

---

・Click on an field -> Select it
・Click on the selected field -> Enter edit mode
・Click outside of the field -> Deselect/exit edit mode

**Comment by peteward** [comment]
Yes, I think the behavior that I find unintuitive is:

* Click on already selected field in edit mode -> exit edit mode

I think if this was removed and you only deselect/exit when clicking outside of the field it would make more sense to me.
