### ISSUE TITLE
Vertical Text Overflow Management in Text Box

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#169]
### Is your feature request related to a problem? Please describe.

Current TextBox height does not have an overflow feature implementation

### Describe the solution you'd like

1. None: Do nothing. The overflowing text is displayed as is. (Current implementation)
2. Truncation: Truncate. The overflowing text is not displayed.
3. Adjusting Font Size: Change the font size to fit within the box. (Similar to the Shrink text on overflow feature in Google Slide)

![CleanShot 2023-05-21 at 17 27 39](https://github.com/pdfme/pdfme/assets/24843808/ac6e3095-e5b7-44fe-977f-5ced8c0cd99c)

ref: [Change how text fits in placeholders & text boxes](https://support.google.com/docs/answer/10364036?hl=en)

### Describe alternatives you've considered

None

### Additional context

I believe this feature can be realized from the following PR

Feature - Dynamic Font Sizing #165 
ref: https://github.com/pdfme/pdfme/pull/165#issuecomment-1556114307

**Comment by hand-dot** [comment]
ref: https://mk.hatenablog.com/entry/2018/04/27/142055

**Comment by hand-dot** [comment]
ref: Vertical text alignment #190

**Comment by hand-dot** [comment]
Memo: No UI, shrink as default

**Comment by peteward** [comment]
Hi @hand-dot,

I don't think this is working as intended yet. We're going to look at #209 soon, which should help implement it, but I  wanted to check something with you first.

This issue was originally about text overflow in general, but it looks like from your point above that this is now only intended for when Dynamic font sizing is enabled, is this correct?

Either way, if you want to implement a 'shrink to fit' approach, then the minimum font size configuration that we currently have is no longer necessary (since you will shrink beyond this down to 0, correct?)
![Screenshot 2023-08-07 at 10 55 37](https://github.com/pdfme/pdfme/assets/7068515/324f2b6a-77c0-4e64-8516-36ae8f909100)

If this is the case then should we remove minimum font size? 
Growing the font up to a maximum is still valid, of course.

Thanks!

**Comment by hand-dot** [comment]
Hey @peteward ,

> I don't think this is working as intended yet. We're going to look at #209 soon, which should help implement it, but I wanted to check something with you first.

![CleanShot 2023-08-08 at 09 56 47](https://github.com/pdfme/pdfme/assets/24843808/67da9009-e1dc-4b69-8a55-cf18b853d83c)

Where specifically is it not working as intended?


> This issue was originally about text overflow in general, but it looks like from your point above that this is now only intended for when Dynamic font sizing is enabled, is this correct?

Yes, it only works when Dynamic Font Sizing is enabled.

> Either way, if you want to implement a 'shrink to fit' approach, then the minimum font size configuration that we currently have is no longer necessary (since you will shrink beyond this down to 0, correct?)

Please do not remove the minimum font size. It is similar to the 'shrink to fit' behavior, but slightly different. In reality, it will shrink down to the value of the minimum font, so the minimum font size setting is necessary, and this value is also needed for the behavior of Dynamic Font Sizing when the width changes. If the user absolutely does not want it to overflow, they can set it to 0 themselves.

**Comment by peteward** [comment]
ah ok, I misunderstood your intentions 😅 

So, just to clarify:

Text overflow can still happen.

1). If you do not use dynamic font size then it is up to the user to ensure text does not overflow by making sure their content and box are the right size.

2). If you do use dynamic font size then you must choose an appropriate minimum font size (or 0) to ensure the content fits.  There will be no automatic adjustment beyond the minimum.


There are a couple of issues that I am working on now for #209 that will ensure correct shrinking behaviour, but the work you have done here is making it easier 👍

**Comment by hand-dot** [comment]
I apologize for causing the misunderstanding.
Thank you for checking!
