### ISSUE TITLE
Cannot read properties of undefined (reading 'widthOfTextAtSize')

### ISSUE THREAD

**Issue by ekansh005** [pdfme/pdfme#181]
### Describe the bug

I had used the PDF template designer hosted on your website. I loaded my existing template of few days old and added a couple of fields by copy paste. Now I downloaded template and tried to generate the PDF with this new file and getting below error:
```
TypeError: Cannot read properties of undefined (reading 'widthOfTextAtSize')\n    at isOverEval (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:205:47)\n    at getOverPosition (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:151:13)\n    at getSplitPosition (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:162:21)\n   …nerator/dist/cjs/src/helper.js:212:30\n    at Array.forEach (<anonymous>)\n    at drawInputByTextSchema (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:203:32)\n    at /Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:281:9\n    at Generator.next (<anonymous>)\n    at /Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:8:71
``` 

Since I hadn't done anything special, I tried to debug the file `@pdfme/generator/dist/cjs/src/helper.js:205:47` and found that `fontValue` is coming as empty/undefined for these new copy paste fields while it is perfectly populated for my old fields.
Then I formatted the downloaded template.json file and found that there is new line of `"fontName": "Roboto"` is added for these fields which is not the case for existing ones. So I just removed this line and the PDF was generated perfectly.

### To Reproduce

- Use any old template
- Add a couple of fields by copy pasting existing fields
- Download the new template.json file
- Use this to generate the PDF file with this new template.json file

### Expected behavior

PDF should have been generated without error as I am not using any custom font. I guess, earlier the default font was Helvatica and now it is Roboto which is causing error.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/generator
- pdfme version: "^1.1.9"
- Operating system: MacOS
- Node.js version or Browser name & version: 19.6.0
```

### Your Error Log

```shell
TypeError: Cannot read properties of undefined (reading 'widthOfTextAtSize')\n    at isOverEval (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:205:47)\n    at getOverPosition (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:151:13)\n    at getSplitPosition (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:162:21)\n   …nerator/dist/cjs/src/helper.js:212:30\n    at Array.forEach (<anonymous>)\n    at drawInputByTextSchema (/Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:203:32)\n    at /Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:281:9\n    at Generator.next (<anonymous>)\n    at /Users/ekanshsaxena/Documents/Dev/KaiRingiPortal/server/node_modules/@pdfme/generator/dist/cjs/src/helper.js:8:71
```

**Comment by hand-dot** [comment]
Hi @ekansh005 

The default font has been changed from Helvetica to Roboto, so please replace Helvetica with Roboto in the template and load it.

**Comment by grigala** [comment]
@hand-dot hi, I'm trying to use this library in the NativeScript enviroment. Everything seems to be fine except the font embedding seems to not work, and the generated PDF is corrupted. When I'm inspecting embedded fonts using i.e. `pdffont` it does not have the default font embedded in it. If I take the corrupted PDF to the service like [Repair-pdf](https://www.ilovepdf.com/repair-pdf) it successfully repairs it.

Do you have any clue what could be a problem? I know that the native mobile environment is not the primary environment of this library, but it should be working regardless, I think.

I have literally tried to copy `drawInputByTextSchema` within my source, and it worked just fine, but when I use `generate` method of `pdfme` it's not working.

**Comment by huypham1411** [comment]
@hand-dot Hi, I got the same issue, can you tell me the reason why this issue occur? I try to log the font value from your playground code and my code to compare and seems like it doesn't different much

here is my log
```
{
    "Roboto-Regular": {
        "fallback": true,
        "label": "Roboto-Regular",
        "url": "https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Me5Q.ttf",
        "data": {}
    }
}
```
and here is the log from playground
```
{
    "NotoSerifJP-Regular": {
        "fallback": true,
        "label": "NotoSerifJP-Regular",
        "url": "/fonts/NotoSerifJP-Regular.otf",
        "data": {}
    },
    "NotoSansJP-Regular": {
        "fallback": false,
        "label": "NotoSansJP-Regular",
        "url": "/fonts/NotoSansJP-Regular.otf",
        "data": {}
    },
    "NotoSansSC-Regular": {
        "fallback": false,
        "label": "NotoSansSC-Regular",
        "url": "/fonts/NotoSansSC-Regular.otf",
        "data": {}
    },
    "ZenKurenaido-Regular": {
        "fallback": false,
        "label": "ZenKurenaido-Regular",
        "url": "/fonts/ZenKurenaido-Regular.ttf",
        "data": {}
    }
}
```

hope you can help, appreciate

**Comment by peteward** [comment]
HI @huypham1411,

Can you confirm your exact problem please?
There appear to be 2 different issues reported here on one closed issue.
If it's different from the original post it would be helpful to open a new issue.

Thanks!
