### ISSUE TITLE
Error when deploying (*Cannot access 'eB' before initialization)

### ISSUE THREAD

**Issue by rnxj** [pdfme/pdfme#186]
### Describe the bug

Hey man, Sorry for not reaching out at the time. Actually, I updated my app to use the newer version of pdfme but still, I was getting the error. 
<img width="1241" alt="image" src="https://github.com/pdfme/pdfme/assets/84446570/79f68673-99ca-4f60-8134-84f26f37353f">

### To Reproduce

For further reference here is my repo to replicate the issue https://github.com/ReuelNixon/certificate-generator (or) visit https://cyscom-certificate.vercel.app/admin/designer. 
This page is actually a protected route so try using  the following cred to login (username: test, password: test)

### Expected behavior

It is expected to display the layout for editing pdf's

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): 1.2.3
- pdfme version: 1.2.3
- Operating system: macos sonoma
- Node.js version or Browser name & version: arc browser
```

### Your Error Log

```shell
Actually, it is not exactly an error that's getting generated. Its is just a bug with =in the package.
```

**Comment by VincentFerreira** [comment]
Hello, I just had the same error after a deployment on Vercel. And I also have many "Uncaught Error: Minified React error #425;" I didn't have locally. Some minification produced this error maybe ?

**Comment by hand-dot** [comment]
Is this still going on at latest pdfme?
