### ISSUE TITLE
Page Crashed error when generating code for an uploaded template

### ISSUE THREAD

**Issue by Lekha30** [pdfme/pdfme#187]
### Describe the bug

My template has 10 pages and I tried creating text fields for the pdf file and hit on generate code. The page just crashed with the error attached in here:

Does the library only support single page pdf?
<img width="549" alt="image" src="https://github.com/pdfme/pdfme/assets/6767299/e916e422-239b-45e3-b125-61798379239c">

### To Reproduce

Provide a multiple page pdf as a Base PDF and try generating code.

### Expected behavior

The code should be generated for the pdf file

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): online try
- pdfme version: https://pdfme.com/template-design
- Operating system: https://pdfme.com/template-design
- Node.js version or Browser name & version: Chrome
```

### Your Error Log

```shell
see attached snapshot
```

**Comment by hand-dot** [comment]
can you provide reproducable codesandbox or stackblitz?

**Comment by hand-dot** [comment]
no reproducable code
