### ISSUE TITLE
Zooming in on viewer cuts off left side of document

### ISSUE THREAD

**Issue by WestynD** [pdfme/pdfme#189]
### Describe the bug

When a document is zoomed far enough that it is wider than it's container, the portion to the left is hidden. This appears to be because the 'starting location' is the center of the document. This allows the user to scroll to the right, but not to the left to view the portion that has been cut off. 

This behavior can easily be observed with the label maker example on the pdfme website [here](https://pdfme.com/demo/address-label-maker). Here are screenshots demonstrating the problem: 

Here the scrollbar at the bottom of the pdf is all the way to the left, but you can't see the left side of the document
![Screenshot 2023-06-21 104157](https://github.com/pdfme/pdfme/assets/70765092/4ad6f6d1-96ee-4e72-804d-83d87e73522f)

Here is the scrollbar all the way to the right and you can see the full right side of the document.
![Screenshot 2023-06-21 104607](https://github.com/pdfme/pdfme/assets/70765092/66c62665-d7ae-441a-9c54-63b21c39d1d2)

The issue appears to be worse if the height of the container is greater than the width. 

### To Reproduce

Zoom in on pdf such that it's width is greater than the width of the container. You will not be able to scroll to see the left side of the document.
The bug appears to be worse if the height of the viewer is equal to or larger than the width.

### Expected behavior

I expect to zoom in and have the option to scroll to the left to see the left side of the document without anything being cut off, just like I can with the right hand side in the  current version. 

### Your Environment

```markdown
- "@pdfme/generator": "^1.1.9" "@pdfme/ui": "^1.1.9"
- Operating system: Windows
- node 16.16.0
- Tested on Firerox, Chrome, and Safari (mobile)
```

### Your Error Log

```shell
none
```

**Comment by WestynD** [comment]
Thank you!

**Comment by hand-dot** [comment]
@peteward  did an amazing job!
