### ISSUE TITLE
Vertical text alignment

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#190]
### Is your feature request related to a problem? Please describe.

We recently contributed dynamic text sizing, however, the growing or shrinking of text is from a baseline position and you will likely need to control this based on the layout of your page.

e.g.:
![Screenshot 2023-06-23 at 12 27 32](https://github.com/pdfme/pdfme/assets/7068515/ee6c5376-fa54-4e05-9ea7-09c4a83dabd9)

text gets shrunk dynamically, but it "moves up" from the desired position (just above the text below) because there is an implicit top alignment to text boxes:

![Screenshot 2023-06-23 at 12 27 59](https://github.com/pdfme/pdfme/assets/7068515/74ef51a1-d18b-46dd-a047-48db18039ea5)

Another use for this feature is that it is sometimes useful if you want to perfectly center text within an available space, to be able to draw a textbox between 2 horizontal planes then just align the text.
![Screenshot 2023-06-23 at 12 30 44](https://github.com/pdfme/pdfme/assets/7068515/3fcda686-c2f6-4461-be98-51691ffdce2b)

### Describe the solution you'd like

Add a vertical alignment option to all text boxes (even without dynamic sizing set). This would contain the options of top, middle, bottom and would adjust the text to the appropriate position within the box.  It would also be respected by dynamic font sizing.

The default option would be top, so all existing templates and schemas would be unaffected.

### Describe alternatives you've considered

-

### Additional context

We will start looking into this contribution.

**Comment by peteward** [comment]
Something simple like this:

![Screenshot 2023-06-23 at 13 07 13](https://github.com/pdfme/pdfme/assets/7068515/51127177-801b-48b5-81be-8ea4a30a1d06)

Alternative labels:

![Screenshot 2023-06-23 at 13 08 21](https://github.com/pdfme/pdfme/assets/7068515/273c3c65-4d64-400e-86c3-0ef670b2fc2e)

**Comment by hand-dot** [comment]
Please use this label.
![](https://user-images.githubusercontent.com/7068515/248263476-273c3c65-4d64-400e-86c3-0ef670b2fc2e.png)

**Comment by hand-dot** [comment]
ref: ref: https://github.com/Hopding/pdf-lib/issues/645#issuecomment-718029496

**Comment by jameshalsall** [comment]
@hand-dot we are still working on this issue, was there a reason you linked to the above comment?

**Comment by hand-dot** [comment]
Hi @jameshalsall 
I just thought getBoundingBox looks useful. It just like a memo. You don't need to use this.

**Comment by peteward** [comment]
Hi @hand-dot, 
We're hoping to have a PR for this ready this week.

**Comment by hand-dot** [comment]
Hey @peteward ,
Wow Cool, I'm waiting a PR.
