### ISSUE TITLE
Bug selecting another schema when you are currently editing another one

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#204]
### Describe the bug

If you are typing into a textarea for a text schema and you click on another one, the new schema doesn't properly get selected.

### To Reproduce

* Click on a text schema to select it
* Click again to start editing the content
* Click a different text schema

### Expected behavior

The currently selected schema should lose focus and the new schema/movable should be selected.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): ui
- pdfme version: latest main / playground
- Operating system: Mac
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
-
```

**Comment by hand-dot** [comment]
![CleanShot 2023-08-13 at 22 43 28](https://github.com/pdfme/pdfme/assets/24843808/fa462fd8-50d6-4ed1-9997-f5e6ebe9ac45)

**Comment by hand-dot** [comment]
Fixed by https://github.com/pdfme/pdfme/pull/232
