### ISSUE TITLE
Add zoom function in @pdfme/ui

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#21]
Reference is to Chrome's PDF viewer.
![CleanShot 2022-02-05 at 15 10 59@2x](https://user-images.githubusercontent.com/24843808/152630938-5cee3473-89c8-4bc0-a4a0-1226b2c34951.png)

**Comment by wahyuandriyanto** [comment]
hi @hand-dot , is there a way to disable zoom control from the Viewer options?

**Comment by tschuehly** [comment]
> hi @hand-dot , is there a way to disable zoom control from the Viewer options?

I would need this aswell. Even just adding an ID to the component so I could hide it myself would be sufficent.
