### ISSUE TITLE
Add New Field button positioning can overlap other content

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#211]
### Describe the bug

In smaller windows the Add New Field button can overlay the content of the page.
This appears to be due to some absolute positioning of the element:

![Screenshot 2023-08-02 at 09 03 35](https://github.com/pdfme/pdfme/assets/7068515/5e177c26-bf68-4f35-8ebe-0f4e72b223ce)

### To Reproduce

* Select a text field for editing
* Reduce the height of your window

### Expected behavior

The Add New Button should sit below the visible content, but not overlap it. 

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): ui
- pdfme version: latest
- Operating system: Mac
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
-
```

**Comment by hand-dot** [comment]
Fixed by https://github.com/pdfme/pdfme/pull/274
