### ISSUE TITLE
Text wrapping in generated PDF leads to overlaid characters

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#218]
### Describe the bug

Sometimes when the text wraps in close to the edge of a line it seems to wrap one character earlier than in the browser. 
Due to separate line rendering, we then place the next line on top of this.

Browser:
![Screenshot 2023-08-08 at 06 38 40](https://github.com/pdfme/pdfme/assets/7068515/ab78f61e-ff42-44e9-ab66-d40565ab8463)

Renderered:
![Screenshot 2023-08-08 at 06 38 57](https://github.com/pdfme/pdfme/assets/7068515/2ab22a32-1ec0-461b-b830-b9a85ae2deb3)

### To Reproduce

As the above example, but I have reproduced this with various text examples

### Expected behavior

The rendered version should ideally wrap exactly as shown in the browser.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): all
- pdfme version: latest main (although I have also tried 10 commits before on a previous branch)
- Operating system: Mac OSX
- Node.js version or Browser name & version: v18.17.0 / Latest Chrome
```

### Your Error Log

```shell
-
```

### Additional context

This might be a regression, or related to a previous issue I found: #174

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/discussions/197

**Comment by peteward** [comment]
I think I may have found the issue whilst working on #209. 

I believe it's [here](https://github.com/pdfme/pdfme/blob/main/packages/generator/src/helper.ts#L221):
```
const getOverPosition = (inputLine: string, isOverEval: IsOverEval) => {
  for (let i = 0; i <= inputLine.length; i++) {
    if (isOverEval(inputLine.slice(0, i))) {
      return i;
    }
  }

  return null;
};
```


`slice(0, i)` excludes the character at position `i`, but this is the position that is returned (we're effectively returning one position too high). 

This means that lines that are split right at the edge of the box can actually exceed it, and I think the PDF writer wraps this character onto the next line.

e.g.
```
------------|
the text ends here
```
In this case instead of returning the 's' character and working backwards to find the previous space, it returns the following space character and thingk it should split between 's' and 'h', thus the line exceeds the box.

The solution would be `slice(0, i+1)`, and it appears to work in my initial tests.

I'm proposing some changes in this area for dynamic font sizing in a PR so I will include this change when ready.

**Comment by hand-dot** [comment]
ref(maybe..?): https://github.com/pdfme/pdfme/issues/144

**Comment by hand-dot** [comment]
@peteward Thank you.
I'm waiting PR

**Comment by peteward** [comment]
This should be fixed now.
