### ISSUE TITLE
Add keep ratio option in image schema

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#22]
ref: https://github.com/hand-dot/labelmake/pull/63

**Comment by lenerey** [comment]
Hey, @hand-dot any updates with this feature?

**Comment by hand-dot** [comment]
Hey @lenerey , Sorry.. not yet

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/pull/384#discussion_r1433345935

**Comment by hand-dot** [comment]
Implemented by https://github.com/pdfme/pdfme/pull/384
