### ISSUE TITLE
Dynamic font resize being called multiple times on UI change

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#228]
### Describe the bug

This [commit](https://github.com/pdfme/pdfme/commit/ebec6cec6eb822863b16aa41c8a2ad5f2b8c6462) to remove `onDynamicResize` has led to the dynamic font resizing being called 8 times per character typed in the TextShema in the main designer:

I noticed that typing was very janky so added a debug comment to when a character was typed and it went up in increments of 8:
<img width="1076" alt="Screenshot 2023-08-13 at 15 11 52" src="https://github.com/pdfme/pdfme/assets/7068515/d8530463-1843-4e45-8fac-e16014fbf000">

### To Reproduce

Type in a text schema

### Expected behavior

`calculateDynamicFontSize` should only be called once per key press.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): ui
- pdfme version: latest main on playground
```

### Your Error Log

```shell
-
```

**Comment by peteward** [comment]
The rendered font size now also does not update when you alter the min and max sizes via the controls, and neither does the actual font size show in the greyed out box

<img width="187" alt="Screenshot 2023-08-13 at 15 37 14" src="https://github.com/pdfme/pdfme/assets/7068515/39d087ae-6883-449f-9938-d4ad90d001dd">

**Comment by peteward** [comment]
It looks like you don't want to show the currently generated font size in the box when greyed out?

```
value={activeSchema.dynamicFontSize ? NaN : (activeSchema.fontSize ?? DEFAULT_FONT_SIZE)}
```

I thought it was quite useful to see what font size is being used by the dynamic calculations, do you not agree?

**Comment by peteward** [comment]
Hey @hand-dot,

If you let me know the intentions of this change then I am happy to look at it tomorrow.

My guess is that you wanted to remove `onDynamicResize` because you do not want the additional coupling of TextSchema to the UI, to make it easier to build the custom schema plugins?

**Comment by hand-dot** [comment]
> My guess is that you wanted to remove onDynamicResize because you do not want the additional coupling of TextSchema to the UI, to make it easier to build the custom schema plugins?
Yes, ref: https://github.com/pdfme/pdfme/issues/225
