### ISSUE TITLE
Designer sidebar layout optimisation

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#248]
### Is your feature request related to a problem? Please describe.

The layout of the designer, with centered content and an overlaid sidebar, does not feel optimal.

You often end up with content overlapped by the sidebar, with wasted space on the left side:

![pdfme-Playground-layout-optimisation](https://github.com/pdfme/pdfme/assets/7068515/c18400ed-4aba-4f02-94ba-4cad2a013aa2)

### Describe the solution you'd like

I'm sure there are many ways of laying this out. 

My suggestion is to separate the sidebar and the designer into different areas, so that the sidebar is not considered part of the 'canvas'.  The sidebar should still be retractable to give a wider, or full viewing experience.

### Describe alternatives you've considered

I'm sure there are lots!

**Comment by hand-dot** [comment]
Hey @peteward , thank you.
I'd like to see your proposal as an image. Could you show it to me through image editing before we proceed with the coding?

**Comment by peteward** [comment]
Yes, absolutely.

This is maybe more of a discussion.

**Comment by peteward** [comment]
With sidebar open, reduced canvas up to the sidebar:

<img width="1037" alt="Screenshot 2023-08-29 at 21 17 21" src="https://github.com/pdfme/pdfme/assets/7068515/f8e04c00-4be6-4253-945b-7dc123de04b0">

with sidebar closed it goes full width:
<img width="1035" alt="Screenshot 2023-08-29 at 21 18 46" src="https://github.com/pdfme/pdfme/assets/7068515/01696cc7-bd98-4b29-ae4c-9ee4bba2838b">

The main canvas and sidebar would scroll independently.

What do you think?

**Comment by hand-dot** [comment]
I think that's fine. 
Just as a note,  pdfme to be useable on mobile too.
so I'd like you to consider that point.

**Comment by peteward** [comment]
ok, thanks for the feedback!

**Comment by sushi2all** [comment]
> Just as a note, pdfme to be useable on mobile too.

I guess that on tablet screens it makes no difference, the solution proposed by @peteward works just fine. 

On smartphones however IMHO it's a poor experience trying to use the `Designer` in general. @hand-dot do you actually have users requesting the Designer being available on smartphones?

**Comment by hand-dot** [comment]
@sushi2all 

I don't think we have any users who would want to use it on smartphones. However, I am reluctant to incorporate conditional branching code using screen size and user-agent into pdfme. 

 It should render correctly regardless of the screen size.


I do believe that @peteward 's proposal is more refined than the current layout, so I am inclined to adopt it.

**Comment by hand-dot** [comment]
@peteward 
Can we close this?
