### ISSUE TITLE
Allow the design/editing of base PDF

### ISSUE THREAD

**Issue by sushi2all** [pdfme/pdfme#262]
### Is your feature request related to a problem? Please describe.

Currently if one wants fixed content on the output, the base pdf must be created outside of the application and then used in the designer when ready.

This breaks the user workflow when making updates.

Considering the library is already able to generate PDFs, why not allow the editing of the fixed part (basePdf)?

### Describe the solution you'd like

#111 and #29 already deal with some base pdf editing features.

Besides that I would love to be able to:
1. Add fixed content
2. Edit page dimensions

# 1. Add fixed content
- Add fixed text
- Add image

The content can then be shown and moved in the canvas the same way of other elements, maybe only with a different color or outline, with the exception that one must explicitly "save" or "cancel" before switching to editing dynamic content. Upon save, the new basePdf gets generated and the template updated.

# 2. Edit page dimensions
Similarly, there could be a `Edit page dimensions` button that allows to resize each page. I understand this may have a higher level of complexity in dealing with existing content that may overflow the new page etcetera. We could at least provide this feature for blank pages. 

### Describe alternatives you've considered

Creating and editing the base pdf in another application.

### Additional context

My application will use `pdfme` to design and print manufacturing labels among other things, so being able to create a custom size pdf from scratch would be very beneficial, not requiring people to use ad hoc software to first create base pdfs every time they need to make an update.

**Comment by jba-tm** [comment]
Any update about this feature?

**Comment by hand-dot** [comment]
No, there are no updates.

However, starting from v3, you can create your own schema. Therefore, by creating things like readOnlyText, readOnlyImage, and line, it should be possible to achieve this.

https://pdfme.com/docs/custom-schemas

**Comment by hand-dot** [comment]
It should be possible to implement custom schemas like the ones mentioned above starting from v3.

If you can't implement it, please find collaborators in the following discussion:
https://github.com/pdfme/pdfme/discussions/288

Is it okay to close this?
