### ISSUE TITLE
Translate all Designer labels

### ISSUE THREAD

**Issue by sushi2all** [pdfme/pdfme#265]
### Is your feature request related to a problem? Please describe.

Currently only part of the Designer labels can be translated. Some can only be shown in english.

### Describe the solution you'd like

Add all labels to the translation setup.

### Describe alternatives you've considered

NA

### Additional context

Willing to give it a shot with some initial help (I don't know React/TS, only used Vue with plain js).

**Comment by hand-dot** [comment]
this is implemented by https://github.com/pdfme/pdfme/pull/323
