### ISSUE TITLE
Same colour combination added to multiple QR Codes if URL's are the same

### ISSUE THREAD

**Issue by steffancarrington** [pdfme/pdfme#266]
### Describe the bug

This is an edge case which may not happen often but is still worth raising an issue for. 

If a user was to add multiple QR Codes to a PDF with the same URL, but specify different `barcolor` and `backgroundcolor` HEX values, both QR Codes would render out in the same colour, this related to the Preview / Generated PDF as the UI displays both QR Codes correctly.

****

### To Reproduce

1. On an existing PDF, Add a new field with the type of 'qrcode'
2. Select a `barcolor` for the QR Code
3. Select a `backgroundcolor` for the QR Code
4. Enter a URL for the QR Code (http:///www.google.com)
5. Repeat the above steps, but selecting different `barcolor` and `backgroundcolor` values for the second QR Code
6. Keep the URL the same
7. Click the 'Preview PDF' button. 

**Generated PDF with incorrect QR Codes**
![Screenshot 2023-09-14 at 12 05 00](https://github.com/pdfme/pdfme/assets/45564901/25d0bfc7-ed9d-4565-911e-0998175af1c9)

### Expected behavior

- Both QR Codes should render in their selected `barcolor` and `backgroundcolor` regardless of the URL specified.

**Correct Rendering of PDF**
![Screenshot 2023-09-14 at 12 05 13](https://github.com/pdfme/pdfme/assets/45564901/e807b354-2a8b-42ba-b1fc-98a34642bba7)

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): ui
- pdfme version: latest
- Operating system: Mac
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
-
```

### Additional context

No response

**Comment by hand-dot** [comment]
I think this problem is caused by a cache.

**Comment by hand-dot** [comment]
getCacheKey is not considering `barcolor` and `backgroundcolor`

ref: https://github.com/pdfme/pdfme/blob/30a0ce2edaebf2c57ab713aafa67bfb712c591ad/packages/generator/src/renders/barcodes.ts#L21C34-L21C45

**Comment by hand-dot** [comment]
> Is caching for long-running processes that generate multiple PDFs using the same schema, and want to avoid regenerating the same content repeatedly?
Yes. 

> The ideal cache key would be schema.type schema.name input value
That's exactly right.

Maybe we should create logic of `getCacheKey` each type pdfRenders, currently we reuse image and barcodes, this is a problem.
