### ISSUE TITLE
Static table feature

### ISSUE THREAD

**Issue by solarpush** [pdfme/pdfme#272]
### Is your feature request related to a problem? Please describe.

Hi, for our use case @pdfme would be great, unfortunately we need to render tables for what looks like an invoice.

### Describe the solution you'd like

I've seen a request for functionality around dynamic tables, but is another approach possible? 

I'm thinking in particular of static rendering where the "table" object would really just be fields with positions calculated to touch each other and a defined border. 

 I'd like to help you develop this feature but I'm not sure I understand how @pdfme works, and I don't have the necessary skills to do it. I'm always available if anyone wants to give me a hand with this.

### Describe alternatives you've considered

Any others.

### Additional context

May be this schema : 
table = {
    row: 1:Number,
    column: 3:Number,
    border: {
      model: "all" || "outside" || "inside" || "none",
      size: Number,
      color: String,
    },
    fields: [
      { index: 0, text: String, name: String },
      { index: 1, text: String, name: String },
      { index: 2, text: String, name: String },
    ],
  };

**Comment by solarpush** [comment]
And thanks you for your work 👍

**Comment by hand-dot** [comment]
https://github.com/pdfme/pdfme/discussions/148

**Comment by solarpush** [comment]
> @solarpush I'm not sure I understand the difference between your idea of "static" table and the dynamic table discussed here: #148 
> 
> How does it simplify the implementation?
> 

If I've understood correctly, the idea behind dynamic tables imposes pagination management if the number of rows provided between them exceeds the page limits. 

On the other hand, a static table whose dimensions are provided in the ui allows you to limit this management as long as the table is created visually and not on the fly from the code.

As with multiple selection, it would be possible to resize the table and its form fields and add borders.

Tell me if it's not clear, I can try to reproduce the behavior I'm talking about on the front end to see how to implement it.

**Comment by hand-dot** [comment]
Hey @solarpush, Thank you create feature request.

> If I've understood correctly, the idea behind dynamic tables imposes pagination management if the number of rows provided between them exceeds the page limits.

You are right. Static table is easier than dynamic one.
Sometime I thought Static table is enough for almost case and i like your idea as a feasibility perspective.

ref: https://github.com/pdfme/pdfme/issues/30

**Comment by hand-dot** [comment]
Version 3 has been feature released, and it should be possible to implement by defining custom schemas.
https://pdfme.com/docs/custom-schemas

Is anyone interested in implementing this?

**Comment by solarpush** [comment]
I can look and try it.

**Comment by hand-dot** [comment]
Close this because it can be achieved by combining [Rectangle Schema](https://github.com/pdfme/pdfme/issues/330) and Text Schema.
