### ISSUE TITLE
Allow null values for optional properties of the template

### ISSUE THREAD

**Issue by sushi2all** [pdfme/pdfme#275]
### Is your feature request related to a problem? Please describe.

To keep data in the backend consistent, I'm storing the field properties as null when they are not set, e.g. `rotation: null`.

When I pass the template to the Designer however the validation throws an error (see #268), because I'm passing `null` values.

### Describe the solution you'd like

Null values, unless required, should simply be ignored.

### Describe alternatives you've considered

As a workaround I'm manually eliminating the null values from the field properties before passing them to the Designer.

### Additional context

Keeping the rotation as an example, the validation is defined here:

https://github.com/pdfme/pdfme/blob/ad7f07e073f2ecac7aa46b1ece59138a8ff3476f/packages/common/src/schema.ts#L34C3-L34C32

I suggest replacing all `.optional()` modifiers with `.nullish()` so that properties are both optional and nullable. See [zod docs](https://zod.dev/?id=nullish)

**Comment by sushi2all** [comment]
Happy to help if this is approved.

**Comment by hand-dot** [comment]
I'll close this as it doesn't warrant a change in data definition for pdfme. 
If your project requires aligning with pdfme entirely, you could fork it, or at least obtain consensus from a majority of users.

If you disagree, please provide reasons for the change that would make it agreeable.

**Comment by sushi2all** [comment]
I understand this may be something not required by other people, but can I know at least if there is any specific reason why those properties should not be accepted if populated with `null`?
