### ISSUE TITLE
Sidebar to consider available height of parent div rather than window

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#286]
### Is your feature request related to a problem? Please describe.

Currently, the editor sidebar fills a height which appears to be related to the overall window, rather than the space that the pdfme editor occupies.

If pdfme is placed within a container (such as the playground) the sidebar is longer than the viewport area and the `Add new field` button is wrapped off the bottom:

<img width="390" alt="Screenshot 2023-10-23 at 15 18 38" src="https://github.com/pdfme/pdfme/assets/7068515/121f114b-34b8-4075-a9a4-7fef88dcef86">

You have to scroll down to see it.

### Describe the solution you'd like

Make the panel and it's children set the the available height of the pdfme designer / form container rather than the window height.

### Describe alternatives you've considered

Ideas for other ways to implement this are welcome. This could also be looked at as part of #248.

**Comment by peteward** [comment]
I don't think this is a bug.

I think you need to make sure the surrounding container for the Designer is the correct height. I have added [a PR for the Playground for this](https://github.com/pdfme/pdfme-playground/pull/4). 

We maybe want to update documentation though, I will check...

**Comment by peteward** [comment]
I will add a PR to the docs with a section to point people to examples of embedding the designer, than I think this can be closed.

**Comment by hand-dot** [comment]
@peteward 
Can we close this issue?
