### ISSUE TITLE
Missing padding-top for Form and Viewer

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#297]
### Describe the bug

![CleanShot 2023-10-29 at 17 01 38@2x](https://github.com/pdfme/pdfme/assets/24843808/9efcd2f2-c2fc-4419-9cdb-f91cf824d05a)

### To Reproduce

Open  Form or Viewer

### Expected behavior

The image has paddings at the top and bottom as shown below.( @pdfme/ui@2.2.1)

<img width="1268" alt="CleanShot 2023-10-29 at 17 04 57@2x" src="https://github.com/pdfme/pdfme/assets/24843808/aee1d585-1b14-4ded-9197-72a5ccbe0700">

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 3.0.0-beta.2
- Operating system: MacOS
- Node.js version or Browser name & version: Google Chrome Version 118.0.5993.117 (Official Build) (arm64)
```

### Your Error Log

```shell
No log
```

**Comment by peteward** [comment]
I removed this in the last PR (unintentionally).
If you are not already looking at it, I can fix this @hand-dot ?

**Comment by hand-dot** [comment]
> I can fix this @hand-dot ?
Of course!
