### ISSUE TITLE
Separating Schema label from code identifier

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#303]
### Is your feature request related to a problem? Please describe.

Currently, in v3 we use the key of the plugins object for displaying to the user:

```
      type: {
        title: 'Type',
        type: 'string',
        widget: 'select',
        props: {
          options: Object.keys(propPanelRegistry).map((label) => ({ label, value: label })),
        },
      },
```

![Screenshot 2023-10-31 at 07 19 17](https://github.com/pdfme/pdfme/assets/7068515/82ffdeea-abee-4948-9ef5-ead0735b2ef7)

### Describe the solution you'd like

I think these labels could be more user-friendly, e.g.:

```
Text
Image
QR Code
Barcode EAN8
Barcode EAN13
````

I think it would also make sense to have a separation between what we call a plugin in the schema JSON versus what we display to the user.  Ideally, we could then allow developers to rename the label used in certain scenarios. e.g. I want to add a new type of text plugin and call it `Text Advanced` and I would like to call the existing text plugin `Text Simple`, regardless of what they are referenced as within the JSON object.

It is my understanding that the key that we currently use comes from here:

```
      designer.current = new Designer({
        domContainer: designerRef.current,
        template: pdfmeTemplate,
        options: { font: fonts },
        plugins: {
          text,
          image,
          qrcode: barcodes.qrcode,
          ean8: barcodes.ean8,
          ean13: barcodes.ean13,
        },
      });
```

The default label should probably be defined within the plugin (and be translatable in future) but it would be ideal if you could also override it at the point of use above.

I may have misunderstood how this works though, I've only just started looking at writing a custom schema 👍 

### Describe alternatives you've considered

-

**Comment by hand-dot** [comment]
I'll check this.
I’d like to be include this to v3.0.0

**Comment by hand-dot** [comment]
I'm currently working on this. It might take 2-3 days as I need to make more extensive modifications to the entire library than I initially thought. Documentation updates will also be needed.

However, I've found a way to simplify not just the labels but also the internal implementation, 
so I plan to include this in the V3 release.

Thank you for making this proposal.

**Comment by hand-dot** [comment]
We can use like this

<img width="765" alt="CleanShot 2023-11-02 at 00 13 29@2x" src="https://github.com/pdfme/pdfme/assets/24843808/a57b1f04-2cff-419c-9433-ce9ab9bfeb0c">

https://pdfme.com/docs/custom-schemas
