### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by isakstarlander** [pdfme/pdfme#321]
### Describe the bug

Hi!

We were looking for a typescript-based package for generating pdfs and really liked the idea of pdfme. However, when we attempted to install the package we get completely stuck at `idealTree:form-render: sill fetch manifest stylis@^4.0.13` during the `npm install`. We've tried to install it on different computers and on different networks but without success. Unfortunately it will mean that we need to continue with another package for the time being, but I wanted to file an issue to see if anyone else experience the same issue.

Using npm v9.5.1 and node v18.16.1

npm i @pdfme/generator

idealTree:form-render: sill fetch manifest stylis@^4.0.13

### To Reproduce

Using npm v9.5.1 and node v18.16.1

Run `npm i @pdfme/generator`

The terminal get stuck consistently on the step `idealTree:form-render: sill fetch manifest stylis@^4.0.13`.

Running the installation with `--verbose` does not provide any additional information.

### Expected behavior

The package would install correctly as other npm packages.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/generator
- pdfme version: 3.0.1
- Operating system: macOS Sonoma 14.0
- Node.js version or Browser name & version: v18.16.1 using npm v9.5.1
```

### Your Error Log

```shell
N/A
```

**Comment by rinturj84** [comment]
Facing the same issue with macOS Sonoma 14.0, and Linux Mint.

**Comment by t5ujiri** [comment]
install succeeded with
```
npm i @pdfme/common@2.2.1 @pdfme/generator@2.2.1
```

Something wrong with major update?

**Comment by hand-dot** [comment]
Can you try this?
https://stackoverflow.com/questions/45433130/npm-install-gets-stuck-at-fetchmetadata
