### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by mauricewegner** [pdfme/pdfme#324]
### Describe the bug

As the peer dependencies of the @pdfme/* packages have been set to `latest` any defined version will print a warning when using pnpm.

<img width="417" alt="image" src="https://github.com/pdfme/pdfme/assets/53715854/36554357-5354-429e-974d-ed0e763402af">

### To Reproduce

Simply install with pnpm, specifying a version (range).

### Expected behavior

Instead of using `latest` as a peer dependency version specify it more explicitly with a version range.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): generator, ui, schemas
- pdfme version: 3.1.1
- Operating system: macOS
- Node.js version or Browser name & version: 18.17 / Chrome
- Package manager: pnpm
```

### Your Error Log

```shell
 WARN  Issues with peer dependencies found
apps/webapp
├─┬ @pdfme/generator 3.1.1
│ ├── ✕ unmet peer @pdfme/common@latest: found 3.1.1
│ └── ✕ unmet peer @pdfme/schemas@latest: found 3.1.1
├─┬ @pdfme/ui 3.1.1
│ ├── ✕ unmet peer @pdfme/common@latest: found 3.1.1
│ └── ✕ unmet peer @pdfme/schemas@latest: found 3.1.1
└─┬ @pdfme/schemas 3.1.1
  └── ✕ unmet peer @pdfme/common@latest: found 3.1.1
```

**Comment by hand-dot** [comment]
Is this still going on at latest pdfme?
