### ISSUE TITLE
Emptying the image field triggers a HTTP request

### ISSUE THREAD

**Issue by dkastl** [pdfme/pdfme#325]
### Describe the bug

When the image of the image field is cleared, a HTTP request to "undefined" is triggered.

### To Reproduce

1. Add a field of type "image"
2. Click the `X` button to clear the image

### Expected behavior

Don't make a HTTP request to `undefined` when clearing the image field.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): 3.1.1
- Operating system: Linux
- Node.js version or Browser name & version: 20.8 / Chrome 119
```

### Your Error Log

```shell
Request URL: http://localhost:3000/undefined
Request Method: GET
Status Code: 404 Not Found
```

### Additional context

[Screencast from 2023-11-21 13-46-57.webm](https://github.com/pdfme/pdfme/assets/227762/4dcad027-9eed-41ae-be24-7b723d85f443)

**Comment by hand-dot** [comment]
@dkastl 
Thank you, I'll check when i have time

**Comment by dkastl** [comment]
Thank you! I found this HTTP request by co-incidence and just created this issue to keep track of it. There is no urgence in solving it.

**Comment by hand-dot** [comment]
memo
https://github.com/pdfme/pdfme/blob/5849e5d8738d3c7f2d4b3372c35e553029d2e8f9/packages/schemas/src/image/uiRender.ts#L47

**Comment by hand-dot** [comment]
Fixed by https://github.com/pdfme/pdfme/pull/351
