### ISSUE TITLE
When switching from one scheme to another, the rotation value did not reset.

### ISSUE THREAD

**Issue by LeandroBanaszeski** [pdfme/pdfme#334]
### Describe the bug

![image018](https://github.com/pdfme/pdfme/assets/45818324/2fbfbaea-574c-4705-8fcb-1773ab7cc8ff)

### To Reproduce

1 - Select any schema in the UI.
2 - Change the rotation to any value.
3 - Select another schema in the UI.

### Expected behavior

Rotation field should reset when changing schema, but it continues with the value of the last selected schema.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 3.1.0
- Operating system: Windows 
- Node.js version or Browser name & version: 18.17.1
```

### Your Error Log

```shell
1 - Select any schema in the UI.
2 - Change the rotation to any value.
3 - Select another scheme in the UI using the SideBar.

Rotation field returns default
```

**Comment by hand-dot** [comment]
this was fixed by bellow code

https://github.com/pdfme/pdfme/blob/cde073cb510e9dadf57bd259b343dddba5bcf3c7/packages/ui/src/components/Designer/Sidebar/DetailView/index.tsx#L68

please wait to merge and release it.

**Comment by hand-dot** [comment]
Fixed: https://github.com/pdfme/pdfme/pull/338
