### ISSUE TITLE
Error when trying to preview PDF if rotation is null

### ISSUE THREAD

**Issue by LeandroBanaszeski** [pdfme/pdfme#342]
### Describe the bug

![image018](https://github.com/pdfme/pdfme/assets/45818324/758d4d2e-017f-404c-86da-8a93c755d248)

Error when trying to preview PDF if rotation is null

In the model it is currently optional, but it does not accept null values, perhaps an option would be to leave it with nullable in the model,
Another option would be, when deleting the value from the rotation input field, it should be removed from Template.

### To Reproduce

1 - Select a schema in the UI
2 - Add value to rotation
3 - Click on the rotation input field and delete the value, leaving it blank
4 - Try previewing the PDF

### Expected behavior

Preview should open correctly

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 3 latest
- Operating system: Windows
- Node.js version or Browser name & version: 18.17.1
```

### Your Error Log

```shell
Uncaught (in promise) Error: [@pdfme/common] Invalid argument:
--------------------------
ERROR POSITION: template.schemas.0.photo.rotate
ERROR MESSAGE: Expected number, received null
```

**Comment by peteward** [comment]
Thanks for reporting this @LeandroBanaszeski !

What do you think about the options @hand-dot ?

Either add `.nullable()` to the schema definition here (and test the impact):

```
export const Schema = z
  .object({
    type: z.string(),
    position: z.object({ x: z.number(), y: z.number() }),
    width: z.number(),
    height: z.number(),
    rotate: z.number().optional(),
  })
```
 
Or when a value is deleted in an input in the UI we remove from the schema?

**Comment by hand-dot** [comment]
@peteward 
This was fixed by bellow code.

https://github.com/pdfme/pdfme/blob/cde073cb510e9dadf57bd259b343dddba5bcf3c7/packages/ui/src/components/Designer/Sidebar/DetailView/index.tsx#L80
