### ISSUE TITLE
Pressing delete twice when editing an input deletes the whole schema

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#343]
### Describe the bug

When editing a schema, if you press the delete key twice while editing a value in an input field it will delete the entire schema.

### To Reproduce

* Select a schema
* Select a any text field, such as width.
* Press delete key twice
* Schema will be deleted.

### Expected behavior

you should be able to press delete within a field without deleting the schema

### Your Environment

```markdown
- pdfme package: @pdfme/ui
- pdfme version: latest main (note, this isn't an issue on pdfme.com/demo
- Operating system: MacOSX
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
no errors
```

### Additional context

I will trace back to see when this was introduced because it's not on pdfme.com/demo

**Comment by hand-dot** [comment]
this problem was fixed by https://github.com/pdfme/pdfme/pull/338
