### ISSUE TITLE
Validating the Schema in the Designer

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#354]
### Is your feature request related to a problem? Please describe.

We embed pdfme in an application that allows end-users to design their own layout. Once they have finished then can either preview or save the schema for use against real data.

Sometimes they may end up in an invalid state:
![Screenshot 2023-12-05 at 09 09 25](https://github.com/pdfme/pdfme/assets/7068515/1e0eb05a-a786-4e15-b664-7c12adc47129)
![Screenshot 2023-12-05 at 09 09 59](https://github.com/pdfme/pdfme/assets/7068515/d09273e1-440f-44ec-b796-29e1b6c90577)

but there is no API that you can check built into pdfme (Designer) that will tell you about the validity of the schema in its current state.

### Describe the solution you'd like

I think it would be great if we could call a function such as `designer.isSchemaValid()` to tell externally whether the schema is valid.  Since we have the capability to embed validation rules into the form-render definitions, it makes sense to pdfme to leverage this. 

### Describe alternatives you've considered

Doing validation externally to pdfme, but this feels like the wrong approach.

**Comment by hand-dot** [comment]
Can't the following code achieve the same thing?

```ts
import { checkTemplate } from "@pdfme/common";

if (checkTemplate(designer.getTemplate())) {
  console.log("valid");
} else {
  console.log("invalid");
}
```

However, I think your suggested `designer.isSchemaValid()` is more user-friendly than the code above.

If you decide to add it, I would like to accept the Pull Request.

**Comment by peteward** [comment]
`checkTemplate` is good, but it doesn't cover many of the attributes within a schema.

It only really covers the base attributes:

```
  .object({
    type: z.string(),
    position: z.object({ x: z.number(), y: z.number() }),
    width: z.number(),
    height: z.number(),
    rotate: z.number().optional(),
    opacity: z.number().optional(),
  })
``` 

so for a test schema it won't validate the background color is a valid hex code.
It also will check for a number on `width` but there's no validation that it's a positive number.

These validation rules we are starting to implement into the UI propPanel JSON. My idea was to use this to drive validation for checking the whole schema. However, this will only work within the UI, so won't be much use for the generator. But it will be useful for the standard workflow where the designer/form will be defining the schema to be used in the generator.

If I have time I will try it tomorrow and share my idea.

**Comment by hand-dot** [comment]
form-render instance has `validateFields` methods.
https://xrender.fun/form-render-mobile/api#forminstance

i'm not sure it useful or not. this is just memo.

**Comment by peteward** [comment]
Closing for now as I think this solution is sufficient
