### ISSUE TITLE
Dynamic font sizing no longer truly dynamic

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#357]
### Describe the bug

Since the implementation of custom schema, and the change to non-react uiRender files, we have lost the benefit of optimized React rendered components.

As a result, schema rendering now replaces the entire content when re-rendered, and to avoid how heavy this is we are now only re-rendering with an `onChange` event for when the editing has finished.

This is a regression in user experience for the text schema, especially when using dynamic text sizing. Previously this would adjust as you type to fit the available space (as per Google Docs, etc):

https://github.com/pdfme/pdfme/assets/7068515/4614533d-9552-4fd9-b0aa-31b727fd1c28

This no longer happens, the sizing of text is only applied once editing has finished and you leave the editor window:

https://github.com/pdfme/pdfme/assets/7068515/970d5705-804b-4157-82ec-26186e936414

I have tried changing the event listener to be onKeyPress, but without the use of React this is far too janky because it rerenders and calculates every aspect of the component on every keypress. There were delays of up to 20 seconds to update the display when I typed for a few seconds with lots of text. There were also issues with `focus()` in doing this if you are typing in the middle of the textbox it will move focus to the end.

### To Reproduce

Type into a text schema

### Expected behavior

Ideally, we would be able to leverage React to support some dynamic updates to the visual display of the schema.

### Your Environment

```markdown
- pdfme package: @pdfme/ui
- pdfme version: latest main
- Operating system: OSX
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
-
```

### Additional context

I don't know if this is easy to resolve.

Would it be possible to allow React components as an alternative to the basic implementations we have of the uiRender file? 

It would be shame to lose the user experience that we used to have.

**Comment by hand-dot** [comment]
Hey @peteward ,
> Would it be possible to allow React components as an alternative to the basic implementations we have of the uiRender file?

I don't think it's a good idea to allow external React components. We would need to ensure that the React version used by pdfme matches the user's runtime, which complicates things. I believe it's simpler to have it written in vanilla JavaScript.

Couldn't we revert to the original UX by re-executing `calculateDynamicFontSize` within the callback of `onChange` mentioned below?
https://github.com/pdfme/pdfme/blob/67439652affbdd70b187a4583283c2cb3bb8b311/packages/schemas/src/text/uiRender.ts#L143

**Comment by hand-dot** [comment]
[Fix Dynamic font sizing no longer truly dynamic #357](https://github.com/pdfme/pdfme/pull/359/commits/88868c95028bfdc2e5478a9a55f7aed8b3b66157)

ref: https://github.com/pdfme/pdfme/pull/359

**Comment by hand-dot** [comment]
fixed by https://github.com/pdfme/pdfme/pull/359
