### ISSUE TITLE
Default position x|y is not set for some types at initial view

### ISSUE THREAD

**Issue by dkastl** [pdfme/pdfme#358]
### Describe the bug

For some types the initial position values `x` and `y` are not set as defined in `propPanel`.
This seems to be the case for 
- image
- signature
- text (only on the online PDF Designer for the 2nd selection)

### To Reproduce

1. Open the designer
2. Add field (and **don't** move the field!)
3. Select between types
4. Observe `x` and `y` input field in the sidebar

### Expected behavior

Set fields in sidebar for `x` and `y` to `0` as for example for `qrcode`.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): probably ui and schema
- pdfme version: https://github.com/pdfme/pdfme/tree/67439652affbdd70b187a4583283c2cb3bb8b311
- Operating system: Linux
- Node.js version or Browser name & version: 20.10 & 119.0
```

### Your Error Log

```shell
Warning: `NaN` is an invalid value for the `top` css style property.
    in div (created by Wrapper2)
    in Wrapper2 (created by Renderer)
    in Renderer (created by Paper)
    in div (created by Paper)
    in div (created by Paper)
    in div (created by Paper)
    in Paper (created by ForwardRef(Canvas))
    in div (created by ForwardRef(Canvas))
    in ForwardRef(Canvas) (created by TemplateEditor)
    in div (created by ForwardRef(Root2))
    in div (created by ForwardRef(Root2))
    in ForwardRef(Root2) (created by TemplateEditor)
    in TemplateEditor
    in MotionWrapper (created by ProviderChildren)
    in ProviderChildren (created by ConfigProvider)
    in ConfigProvider (created by AppContextProvider_default)
    in AppContextProvider_default
```

### Additional context

[Screencast from 2023-12-07 01-25-48.webm](https://github.com/pdfme/pdfme/assets/227762/47ca102d-e4c0-47ec-9040-47dfb4909415)

This also happened in a plugin I'm building, where I set to

```
const propPanel = {
  schema: {},
  defaultValue: '',
  defaultSchema: {
    type: 'mapimage',
    position: { x: 10.0, y: 10.0 },
    width: 80.0,
    height: 60.0
  },
};
```
Whether the position is `0` or a value like `10.0` it does not set the position correctly.

**Comment by peteward** [comment]
This could be fixed by #367
