### ISSUE TITLE
German language support PR

### ISSUE THREAD

**Issue by olga-krayevska** [pdfme/pdfme#362]
### Is your feature request related to a problem? Please describe.

I’d like to add PR with German language support.  

### Describe the solution you'd like

I’ve got ERROR: Permission to pdfme/pdfme.git denied.

### Describe alternatives you've considered

How can I contribute?

**Comment by hand-dot** [comment]
Hey @olga-krayevska ,

Cool, Can you read this? https://github.com/firstcontributions/first-contributions?tab=readme-ov-file#fork-this-repository

**Comment by olga-krayevska** [comment]
> Hey @olga-krayevska ,
> 
> Cool, Could you check this readme? https://github.com/firstcontributions/first-contributions?tab=readme-ov-file#fork-this-repository

got it, thank you @hand-dot

**Comment by olga-krayevska** [comment]
@hand-dot my PR: https://github.com/pdfme/pdfme/pull/364

**Comment by hand-dot** [comment]
Great! @olga-krayevska , i'll check it tomorrow.
