### ISSUE TITLE
Deleting a core value from the UI (e.g. X or Y pos), or setting to 0 will remove from the schema

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#366]
### Describe the bug

If you have a 0 value for some parameters they will be removed from the resulting schema, which then becomes invalid and won't load

### To Reproduce

* Create a text schema
* Delete the 'Y' value for it in the UI
* Download the template for the Schema
* The y value will be missing, e.g.:

```
{"schemas":[{"name":{"type":"text","position":{"x":24.77},"width":77.77,"height":38.01,....
```

### Expected behavior

You should not be able to fully delete a numeric required value.
Any attempt to delete it should 0 the value, and this should be retained when the schema is saved.

### Your Environment

```markdown
- pdfme package: @pdfme/ui
- pdfme version: 3.1.5
- Operating system: Mac OSC
- Node.js version or Browser name & version: Chrome latest
```

### Your Error Log

```shell
On loading a broken schema:


Error: [@pdfme/common] Invalid argument:
--------------------------
ERROR POSITION: template.schemas.0.name copy.position.y
ERROR MESSAGE: Required
--------------------------
    at L6 (index.js:159:10)
    at zbe (index.js:161:314)
    at new ENe (index.js:266:9838)
```

You will also get a NaN error for applying padding to the text.
```


### Additional context

_No response_

**Comment by peteward** [comment]
Continuing with 'y' as an example, you can see that when you delete the value in the input field, it gets sent as null (which makes sense I guess).

![Screenshot 2023-12-14 at 16 09 18](https://github.com/pdfme/pdfme/assets/7068515/0d3c2d63-9702-4125-9ba5-2b8387bfb416)

This value is stripped out of the schema.

**Comment by peteward** [comment]
ok the bug is here:

https://github.com/pdfme/pdfme/blob/main/packages/ui/src/components/Designer/Sidebar/DetailView/index.tsx#L80

This is changing 0 to undefined, which we don't want to do for required fields.

Was the intention here to use 0 to disable/remove the field if it's optional @hand-dot ?

**Comment by peteward** [comment]
I think an ideal solution would be to check if a field is required according to it's zodSchema, and only if it is NOT required would we allow it to be set to undefined.

**Comment by hand-dot** [comment]
> ok the bug is here:
> 
> https://github.com/pdfme/pdfme/blob/main/packages/ui/src/components/Designer/Sidebar/DetailView/index.tsx#L80
> 
> This is changing 0 to undefined, which we don't want to do for required fields.
> 
> Was the intention here to use 0 to disable/remove the field if it's optional @hand-dot ?

I added this code a few weeks ago to solve https://github.com/pdfme/pdfme/issues/342.
