### ISSUE TITLE
Adding an image is confusing that you need to clear the placeholder

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#378]
### Describe the bug

I thought the image schema was broken because I didn't realise you have to clear the existing placeholder before you can actually add an image.

### To Reproduce

* Add schema
* Select type = Image
* You will see the following and it's not obvious what to do:

![Screenshot 2023-12-18 at 10 42 24](https://github.com/pdfme/pdfme/assets/7068515/5a477682-b5d9-45fd-a59c-3e71a8c37efd)

### Expected behavior

* When you add or change a schema type to image it should assume it's empty and offer the upload facility.

### Your Environment

```markdown
- pdfme package: @pdfme/ui
- pdfme version: latest
```

### Your Error Log

```shell
-
```

**Comment by hand-dot** [comment]
Good point... 
Already, I had forgotten the feeling of freshness and did not realize it.
