### ISSUE TITLE
Support bold and italic in text schema

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#396]
### Is your feature request related to a problem? Please describe.

Currently, our text schema uses a single font to render text, which makes it impossible to render different font styles.

### Describe the solution you'd like

We need to either extend the text schema or create a different schema to allow changing styles at any desired location.

### Describe alternatives you've considered

At present, this can be achieved by changing the font, but it requires using a different schema for each style. Combining multiple styles is not possible.

**Comment by qroulland** [comment]
When i'm trying to import bold font, the generator always render as regular... How am I supposed to use a bold font?
