### ISSUE TITLE
Firefox 121.0 (64-Bit) Uncaught (in promise) DOMException: An invalid or illegal string was specified

### ISSUE THREAD

**Issue by holaa2019** [pdfme/pdfme#399]
### Describe the bug

By just visiting https://pdfme.com/ with Firefox 121.0 (64-Bit), or likewise using the form feature, I get 'Uncaught (in promise) DOMException: An invalid or illegal string was specified'. This prevents any user input into the form. The cursor is visible, but nothing is added in the fields.

For Chrome, Edge, Opera I don't see this.

![grafik](https://github.com/pdfme/pdfme/assets/47902201/3f6bf599-0ce6-4471-8b00-3440505b5c14)
![grafik](https://github.com/pdfme/pdfme/assets/47902201/48e2db76-135e-40eb-a0c4-16b9d84e1daa)

### To Reproduce

just visit https://pdfme.com/  with the Firefox browser (current version)

### Expected behavior

no DomException error, taking user inputs

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version: 3.2.0
- Operating system: Windows 10, android 9
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
Uncaught (in promise) DOMException: An invalid or illegal string was specified
    ui https://pdfme.com/assets/js/1df93b7f.2c8dd440.js:1
    A https://pdfme.com/assets/js/586.0415d668.js:1
    hs https://pdfme.com/assets/js/586.0415d668.js:1
    Fl https://pdfme.com/assets/js/586.0415d668.js:1
    unstable_runWithPriority https://pdfme.com/assets/js/586.0415d668.js:1
    qi https://pdfme.com/assets/js/586.0415d668.js:1
    Pl https://pdfme.com/assets/js/586.0415d668.js:1
    Ol https://pdfme.com/assets/js/586.0415d668.js:1
    N https://pdfme.com/assets/js/586.0415d668.js:1
    onmessage https://pdfme.com/assets/js/586.0415d668.js:1
5 1df93b7f.2c8dd440.js:1
    ui https://pdfme.com/assets/js/1df93b7f.2c8dd440.js:1
    AsyncFunctionNext self-hosted:852
    (Async: async)
    A https://pdfme.com/assets/js/586.0415d668.js:1
    hs https://pdfme.com/assets/js/586.0415d668.js:1
    Fl https://pdfme.com/assets/js/586.0415d668.js:1
    unstable_runWithPriority https://pdfme.com/assets/js/586.0415d668.js:1
    qi https://pdfme.com/assets/js/586.0415d668.js:1
    Pl https://pdfme.com/assets/js/586.0415d668.js:1
    Ol https://pdfme.com/assets/js/586.0415d668.js:1
    N https://pdfme.com/assets/js/586.0415d668.js:1
    onmessage https://pdfme.com/assets/js/586.0415d668.js:1
```

**Comment by AdamD2L** [comment]
The bug is open ... Is it going to be corrected soon ?

**Comment by hand-dot** [comment]
@holaa2019 
The latest version of pdfme should work correctly on Firefox. Can you check it and close the issue if there are no problems?

**Comment by holaa2019** [comment]
Works, Looks awesome! Thanks

**Comment by holaa2019** [comment]
now closed
