### ISSUE TITLE
Add a Left Sidebar for Placing Schemas

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#400]
### Is your feature request related to a problem? Please describe.

Currently, in pdfme, schemas are added by clicking the "Add new field" button. This button is located at the bottom of the right sidebar, and I don't think the user experience is particularly good. Not only is the location not optimal, but for example, if you want to add an image schema, you need to change the schema type after adding it.

### Describe the solution you'd like

Add a left sidebar, and place icons for each schema type on this sidebar. Allow schemas to be placed by dragging and dropping these icons.

![CleanShot 2023-12-30 at 15 32 54](https://github.com/pdfme/pdfme/assets/24843808/dd61bf1a-6740-4111-8293-a64cdb6dac68)

ref: https://pdfgeneratorapi.com/templates/free-templates/personalized-quote -> Edit template button

### Describe alternatives you've considered

None.

### Additional context

I have been thinking about this UX improvement for a while, but it required adding icons to existing schemas and would be a breaking change, so I haven't been able to implement it. However, with many breaking changes occurring in V4, I would like to take this opportunity to implement it.

**Comment by peteward** [comment]
I really like this.

It also increases the vertical real-estate of the right-hand sidebar, which can scroll off the screen for smaller resolutions.

**Comment by hand-dot** [comment]
ref: https://docs.dndkit.com/api-documentation/droppable

**Comment by vpn-dev** [comment]
Any work in progress on this @hand-dot 
?

**Comment by hand-dot** [comment]
Hi @vpn-dev 

here is pr: https://github.com/pdfme/pdfme/pull/452
implementation is done.

this feature will be release as v4

**Comment by vpn-dev** [comment]
Cool @hand-dot , any idea when V4 will be published?

**Comment by hand-dot** [comment]
@vpn-dev 
we need to resolve https://github.com/pdfme/pdfme/issues?q=is%3Aissue+is%3Aopen+label%3Atable
