### ISSUE TITLE
changeSchemas function when used on custom widgets in extends text plugin removing all other properties of text applied to it.

### ISSUE THREAD

**Issue by vpn-dev** [pdfme/pdfme#416]
### Describe the bug

I extended text plugin with some extra properties like backgroundColorFromTheme in which colors are shown in select menu, i added onChange handle for this select in propPanel which uses changeSchemas function to update value of original background color property but it also changes other properties of text which are not commited to earlier version.

### To Reproduce

- add some custom widget in schemas like select
- add onChange on that select  in which call changeSchemas to change original property of text

### Expected behavior

It should only change shemas that are provided in function params not all ...

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): all packages 3.2.1
- pdfme version: 3.2.1
- Operating system: Ubuntu 22
- Node.js version or Browser name & version: node 18.19.0 chrome
```

### Your Error Log

```shell
No error log its, just wrong output kind of thing
```

**Comment by vpn-dev** [comment]
@hand-dot can you have a look at this? we can discuss this issue..

**Comment by hand-dot** [comment]
Hey @vpn-dev, 

Could you show me the code?

**Comment by vpn-dev** [comment]
Absolutely here is screenshot of code
![font-color-plugin](https://github.com/pdfme/pdfme/assets/37739139/3605876d-f8db-40dd-9331-4615e98511d9)

**Comment by vpn-dev** [comment]
@hand-dot as you can see in the above code snippet i have extended text schema with fontColorFromTheme property, on which I have added onChange to change actual fontColor property of text schema but this is causing all active changes to schema go away. if none is selected from fontColorFromTheme property I am just resetting the fontColor Value otherwise I am extracting the value from my theme object which is a material ui theme object , I am doing this to use same template for multiple themes.  Can you suggest better way

**Comment by hand-dot** [comment]
@vpn-dev 

The code looks good, and I understand what you are trying to achieve.

Please share a screenshot or the executable code to show exactly what behavior you are experiencing. 
It would be helpful if you could share it using a service like the one below, as it makes it easier to test. 

Could you fork the following code, install the latest pdfme 3.2.2, incorporate your plugin, and then share it with me?
https://stackblitz.com/~/github.com/pdfme/pdfme-playground

**Comment by vpn-dev** [comment]
@hand-dot I have made fork of this repo with my changes in it

**Comment by vpn-dev** [comment]
[Kazam_screencast_00004.webm](https://github.com/pdfme/pdfme/assets/37739139/739f1b09-a63a-4500-9d7c-df1f1a1c464a)
@hand-dot  you can see the issue in above video as I said when I am changing newly added select widgets i/e backgroundFromTheme and fontColorFromTheme other active changes on text but which are not committed yet are lost

**Comment by hand-dot** [comment]
@vpn-dev 
Thank you. I was able to observe the same behavior on my computer as well. 
This is a bug. I will investigate the cause and aim to fix it.

**Comment by hand-dot** [comment]
@vpn-dev 
Can you check bellow?

- preview: https://stackblitz.com/~/github.com/hand-dot/pdfme-playground
- code changes: https://github.com/vpn-dev/pdfme-playground/commit/1e26b6a4b19f398f6ac7fd62c976ffb197e43d73

---

It seems that overriding `onChange` and calling `changeSchemas` disrupts the existing change processes. The `UseDynamicSizeWidget` is operating as intended by skipping the existing change processes entirely due to `bind: false`.

In this fix, rather than overriding `onChange`, I have set it up to reflect the theme color during the initialization of `propPanel.schema`.

**Comment by vpn-dev** [comment]
Hey @hand-dot thanks a lot, this solution completely works.. :100:
