### ISSUE TITLE
UI bundle size optimization: development react/react-dom files included in UI prod build fix

### ISSUE THREAD

**Issue by olga-krayevska** [pdfme/pdfme#423]
### Is your feature request related to a problem? Please describe.

Hello @hand-dot, again, thank you for great lib) 
I’ve noticed rather big bundle size of UI package: 
![pdfme-issue-1](https://github.com/pdfme/pdfme/assets/117985670/1aaf1a33-a1ac-49b8-964c-4cf8584c1e23)

I’ve checked it with bundle visualizer and there are both development and production react and react-dom files included:
![pdfme-issue-2](https://github.com/pdfme/pdfme/assets/117985670/0f537c66-df0a-4135-a61e-b006e93931c0)

### Describe the solution you'd like

I’ve checked Vite docs for possible solution for that and have found that defining process.env.NODE_ENV in Vite configs fixes it: 
![pdfme-issue-3](https://github.com/pdfme/pdfme/assets/117985670/95381ccf-e2cd-43b2-bad7-7626ba185668)
![pdfme-issue-4](https://github.com/pdfme/pdfme/assets/117985670/3aa6c8c3-a440-4cbc-9801-b4161fb1a9fb)
only production files are included

my PR: https://github.com/pdfme/pdfme/pull/422

### Describe alternatives you've considered

I've got no alternative solutions

**Comment by hand-dot** [comment]
Hey @olga-krayevska,
I'm happy you contributed again. Thank you.

I've merged the PR, so I'll close it. It's scheduled to be included in the next release.
