### ISSUE TITLE
🔥🔥🔥 [Form & Generator] The page break does not account for pages beyond the second page.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#429]
- ![Untitled](https://github.com/pdfme/pdfme/assets/24843808/e5643df2-c87e-43cf-9471-34ae7f846a7a)
- It is believed that this issue is occurring due to a mistake in the calculation of `getDynamicTemplate`.
  - https://github.com/pdfme/pdfme/blob/cf7e8b978f872ec0aea9c64e5f483716f0089cad/packages/common/src/helper.ts#L237
  - ref: TODO Write test

---
Related : https://github.com/pdfme/pdfme/issues/428

**Comment by kiamesdavies** [comment]
@hand-dot any luck with resolving this

**Comment by hand-dot** [comment]
@kiamesdavies struggling...

**Comment by kiamesdavies** [comment]
@hand-dot Damn I can imagine it breaking other stuffs as well. Took a quick look couple of months ago, and also saw that its a serious challenge.

**Comment by vpn-dev** [comment]
I am also working on same issue from a week. trying to break tables page by page like one page in actual template will generate lets say 4 pages with data populated in tables and other widgets on same page shifted correctly . any other fields on other pages in actual template should start from new page in new template as well. I am working based to achieve this..

**Comment by vpn-dev** [comment]
@hand-dot  Found one more issue related to vertical alignment of bodyStyles in table i think its not calculating correct cell height resulting in overflowing the text in cell

**Comment by vpn-dev** [comment]
> I am also working on same issue from a week. trying to break tables page by page like one page in actual template will generate lets say 4 pages with data populated in tables and other widgets on same page shifted correctly . any other fields on other pages in actual template should start from new page in new template as well. I am working based to achieve this..

[Uploading pdfme-working-table.webm…]()


 I achieved this result as shown in the video above as per my assumption of single page adjustments we will split and adjust position for each original page individually , and then other page schemas will start from new page always this is helpful as if user is building pdf with multiple pages they need that content on new page so we should start from new page for each actual page and then split and adjust dynamic content accordingly

**Comment by vpn-dev** [comment]
[Uploading pdfme-working-table.webm…]()

**Comment by hand-dot** [comment]
@vpn-dev 

> is this ok or you were trying something else?

Wow! Looks Okay, Can you submit PR?

**Comment by vpn-dev** [comment]
@hand-dot do i have to create a fork and then raise a pr, because its showing me unauthorized to push any branch on pdfme main repo

**Comment by peteward** [comment]
Yes, create a fork 👍

**Comment by vpn-dev** [comment]
https://github.com/pdfme/pdfme/pull/582
