### ISSUE TITLE
🔥 [Form] The form re-renders when inputting data.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#432]
- ref: TODO Set to true only if the execution of getDynamicTemplate, such as for a table, is required.
- ref: TODO Calling onChange triggers re-rendering, causing the focus to be lost
-  ![CleanShot_2024-01-20_at_16 47 18](https://github.com/pdfme/pdfme/assets/24843808/a16c651f-0256-4efc-82e0-8c006183b917)

**Comment by peteward** [comment]
Hi @hand-dot,

Is this still an issue? I tried this out on latest v4 and couldn't see the problem

**Comment by hand-dot** [comment]
I can't repro at this time.
so i'll close this issue.

thank you!

**Comment by npyl** [comment]
Still an issue for me.
