### ISSUE TITLE
🔥🔥 [Form & Generator] Multiple tables were misaligned when a new page was created.

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#433]
- [template.json](https://github.com/pdfme/pdfme/files/14391487/template.json)
- ![CleanShot 2024-01-23 at 11 38 43](https://github.com/pdfme/pdfme/assets/24843808/e8e14672-bfa8-40bf-b9aa-0a49b294d00e)

**Comment by hand-dot** [comment]
Fixed by https://github.com/pdfme/pdfme/pull/590

**Comment by kiamesdavies** [comment]
@hand-dot I think there's a regression in the v5 of the table, adding a new row, doesnt push the other elements down, but cover them as seen in the video attached. 

https://github.com/user-attachments/assets/9084eab1-5a0f-4d9d-8914-729df2203368

**Comment by kiamesdavies** [comment]
I also used the exact same template above

**Comment by kiamesdavies** [comment]
my bad, the issue only appears when using the designer and not the form
