### ISSUE TITLE
template-design not working in firefox

### ISSUE THREAD

**Issue by AdamD2L** [pdfme/pdfme#438]
### Describe the bug

Text fields are not working in the https://pdfme.com/template-design in firefox

### To Reproduce

go to https://pdfme.com/template-design
Create a text field
Try to enter text in the text field

### Expected behavior

Text field displays text

### Your Environment

```markdown
- firefox 123.0 64 bits
```

### Your Error Log

```shell
Uncaught (in promise) DOMException: An invalid or illegal string was specified
    ui https://pdfme.com/assets/js/43b07d87.03c35d38.js:1
```

### Additional context

Quite urgent ... makes the tool quite unsusable for many users :-(

**Comment by valushagrinchik** [comment]
The same as #399

**Comment by valushagrinchik** [comment]
`textBlock.contentEditable = 'true' ` instead of `textBlock.contentEditable = 'plaintext-only' ` in packages/schemas/src/text/uiRender.ts:120 should help

**Comment by hand-dot** [comment]
Hey @valushagrinchik 
Thank you for the investigation. 

The reason for setting `textBlock.contentEditable = 'plaintext-only'` is to prevent styles from being pasted with the text. 
You are right. It seems it doesn't work in Firefox.
![CleanShot 2024-03-12 at 09 17 49@2x](https://github.com/pdfme/pdfme/assets/24843808/a500acf7-f2c2-4c72-8e5a-1b5c74d92568)


Let's think about a workaround. The scope of the fix should be small, so it shouldn't be hard to resolve this issue.

Do you have any ideas?

**Comment by valushagrinchik** [comment]
Ok, so that we need to also overwrite paste event to get text-only from user input
`
    textBlock.addEventListener('paste', (e: ClipboardEvent) => {
      e.preventDefault();
      const paste = e.clipboardData?.getData('text');
      const selection = window.getSelection();
      if (!selection?.rangeCount) return;
      selection.deleteFromDocument();
      selection.getRangeAt(0).insertNode(document.createTextNode(paste || ''));
      selection.collapseToEnd();
    });
`

**Comment by hand-dot** [comment]
Thanks @valushagrinchik 

Can you create PR?

**Comment by hand-dot** [comment]
@AdamD2L  @valushagrinchik 
The latest version of pdfme should work correctly on Firefox. Can you check it and close the issue if there are no problems?
