### ISSUE TITLE
Placeholder, Expression

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#439]
### Is your feature request related to a problem? Please describe.

Example image
![image](https://github.com/pdfme/pdfme/assets/24843808/709e3df8-8557-4150-9bc3-9bfa94beaa6f)

---

I don't have a concrete idea of how to realize this yet.

Perhaps a template engine like [Handlebars](https://handlebarsjs.com/) could operate at render time?
However, there is a clear need from users. This might also involve breaking changes, so it might be included in V4 depending on circumstances.

- ref: https://github.com/pdfme/pdfme/issues/437
- ref: https://github.com/pdfme/pdfme/pull/388
- ref: https://github.com/pdfme/pdfme/discussions/208#discussioncomment-6594913

### Describe the solution you'd like

- Addding preprocessing and custom plugins for PDF generation.
- Adding page break processing when text overflows.

### Describe alternatives you've considered

Add a process to replace placeholders before calling the generate function.

**Comment by peteward** [comment]
https://github.com/pdfme/pdfme/pull/466 achieves this. Let me know if you were thinking of something different.

**Comment by hand-dot** [comment]
Let's think UI of Form mode.

Currently, your PR doesn't have Implementation right?

**Comment by peteward** [comment]
Yes, I can add one though

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/pull/502
