### ISSUE TITLE
Import pdfme with a script element

### ISSUE THREAD

**Issue by marcusx2** [pdfme/pdfme#456]
### Is your feature request related to a problem? Please describe.

I want to use pdfme by importing it with a [script](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) element. I don't use nodejs, typescript, webpack, etc.

### Describe the solution you'd like

I want to import pdfme with the script tag like `pdfjs`

```
<script type="module">
import pdfjsDist from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.0.379/+esm'
</script>
```

or `pdf-lib`
`<script src="https://unpkg.com/pdf-lib"></script>`

### Describe alternatives you've considered

None

**Comment by hand-dot** [comment]
This is not a feature request. 
Please continue at https://github.com/pdfme/pdfme/discussions/455

**Comment by marcusx2** [comment]
@hand-dot I understand, can you help me on that discussion? I'd greatly appreciate it. Thanks...
