### ISSUE TITLE
Add Schema Checkbox

### ISSUE THREAD

**Issue by ivanprejoles** [pdfme/pdfme#457]
### Is your feature request related to a problem? Please describe.

I was trying to make a form with checkbox using a text schema with check symbol and some conditional statement, unfortunately it wasn't working

### Describe the solution you'd like

Probably a checkbox schema that would display and hide a checkmark, x, or simply fill the box whenever the user clicks toggle the box

### Describe alternatives you've considered

It's also better to add boolean type "visible" on each item's object for conditional statement.

ref: https://github.com/pdfme/pdfme/issues/570

**Comment by hand-dot** [comment]
Thank you for your feature request.

I have seen requests for checkboxes multiple times in the discussion threads below, so while I can't promise when it will be implemented, I do intend to address it.

https://github.com/pdfme/pdfme/discussions/288

**Comment by hand-dot** [comment]
working on it
