### ISSUE TITLE
All jest test suites failed after adding @pdfme to the project

### ISSUE THREAD

**Issue by zowebs** [pdfme/pdfme#48]
Hello,
I added this fantastic package into my project. Everything went smooth until I proceed to testing. When I ran jest tests, this error showed as a result of every suite. Any solution?
<img width="716" alt="image" src="https://user-images.githubusercontent.com/54768925/157514600-cd0bf0ac-e073-4616-bcf7-be33ee652d80.png">

**Comment by hand-dot** [comment]
@zowebs 
Hi! Thank you for your report.

I'll check this problem.
If you can please share minimal reproduction.

**Comment by hand-dot** [comment]
Ref https://github.com/pdfme/pdfme/pull/62
