### ISSUE TITLE
Basepdf & table

### ISSUE THREAD

**Issue by tomfranciseu** [pdfme/pdfme#486]
### Describe the bug

Uploading a base pdf, including a table and generating the pdf does not work.  It seems because the margins are not included in a base pdf.  The error message in the console is: Error: [@pdfme/schema/table] Blank PDF is not supported.  

### To Reproduce

Upload this in the designer as background and press: Generate PDF.  (the same happens in coding)
[background.pdf](https://github.com/user-attachments/files/15856273/background.pdf)

### Expected behavior

PDF should be generated

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):schema/table
- pdfme version: 4.0.0
- Operating system: Windows
- Node.js version or Browser name & version: 20.12 (edge & brave)
```

### Your Error Log

```shell
Uncaught (in promise) Error: [@pdfme/schema/table] Blank PDF is not supported
    at createSingleTable (index-082b0977.js:1286:87489)
    at uiRender (index-082b0977.js:1286:92877)
    at index-082b0977.js:787:93
    at Ii (index-082b0977.js:113:81167)
    at Vj (index-082b0977.js:115:6592)
    at at.unstable_runWithPriority (index-082b0977.js:105:4215)
    at cg (index-082b0977.js:113:39057)
    at Dj (index-082b0977.js:115:6340)
    at yj (index-082b0977.js:113:92432)
    at index-082b0977.js:113:39371
```

**Comment by Elendiar** [comment]
Same issue, `isBlankPdf `helper function check that `basePdf` is an object with w, h and padding.
But i need to use pasePdf standartized template from pptx presentation in album orientation.

**Comment by hand-dot** [comment]
This is the intended behavior.
The table can cause a page break, but if the basePdf is a custom PDF, it cannot shift other elements down when a page break occurs, so it results in an error.

If there are any issues with the current implementation, let's discuss them here.
Fortunately, the table schema is still in beta.

**Comment by hand-dot** [comment]
> Ah I see. Maybe that error message should say Custom PDF is not supported?
Yes... The error message was causing confusion.

We've received similar feedback, and we're considering making it possible to add tables to any basePdf.
One concern is that when basePdf is base64 PDF data, we haven't yet thought of a satisfactory way to handle page breaks.
If you have any ideas, please let us know.

Ref: 
- https://github.com/pdfme/pdfme/issues/473
- https://github.com/pdfme/pdfme/issues/479
- https://github.com/pdfme/pdfme/issues/482
- https://github.com/pdfme/pdfme/issues/486

**Comment by hand-dot** [comment]
Modified the implementation to issue a warning (console.warn) indicating that features like page breaks are unavailable, instead of throwing an error. This allows basePdf to add tables in any situation.

ref: https://github.com/pdfme/pdfme/pull/592
