### ISSUE TITLE
Request to Remove Default "Field List" and Enable Custom Metadata

### ISSUE THREAD

**Issue by Aleezah1429** [pdfme/pdfme#487]
### Describe the bug

I need the flexibility to customize the field list based on our specific metadata requirements, but the current implementation does not support this.

### **Current Implementation:**
<div id='container' ref={containerRef} style={{width: '100%', height: '100vh'}}></div>

### **Issue Details:**
The "field list" type code is not present, limiting customization.
We need to replace the default field list with a custom list from our metadata.

![image](https://github.com/pdfme/pdfme/assets/64039135/cdece576-6a17-4e21-98c8-bf2113388a92)

### Expected behavior

Ability to remove the default field list and dynamically generate a new field list based on provided metadata.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 4.0.2
- Operating system: Windows
- Node.js version: 16.11.27
```

### Your Error Log

```shell
None
```

### Additional context

This flexibility will enhance pdfme's usability for projects requiring specific field customizations and allow for a more dynamic user experience.

Thank you for considering this request. I look forward to any updates or suggestions on achieving this customization.

**Comment by peteward** [comment]
Hi there!

What do you mean "from your metadata"? Is this different from the schema (which the fields are generated from)?

You are welcome to open a PR if you think you can open up the code for modifications cleanly.
