### ISSUE TITLE
Error when following the tutorial setup

### ISSUE THREAD

**Issue by ddtbuilder** [pdfme/pdfme#488]
### Describe the bug

followed the getting started page here:

[https://pdfme.com/docs/getting-started](url)

I am using rollup and when I use:

import { generate } from '@pdfme/generator';

this error shows up:

 code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/node_modules/unicode-properties/dist/module.mjs',
  pos: 48,
  loc: {
    column: 7,
    file: '/node_modules/unicode-properties/dist/module.mjs',
    line: 2
  },
  frame: '1: import $bdjGp$base64js from "base64-js";\n' +
    '2: import $bdjGp$unicodetrie from "unicode-trie";\n' +
    '          ^\n' +
    '3: \n' +
    '4: function $parcel$interopDefault(a) {',

etc....

### To Reproduce

import any of the pdfme functions and save the .js file...rollup (using watch) chokes with above error

### Expected behavior

clean compile

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): generator
- pdfme version: latest
- Operating system: MacOS
- Node.js version or Browser name & version: Node 21.6.1
```

### Your Error Log

```shell
code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '/node_modules/unicode-properties/dist/module.mjs',
  pos: 48,
  loc: {
    column: 7,
    file: '/node_modules/unicode-properties/dist/module.mjs',
    line: 2
  },
  frame: '1: import $bdjGp$base64js from "base64-js";\n' +
    '2: import $bdjGp$unicodetrie from "unicode-trie";\n' +
    '          ^\n' +
    '3: \n' +
    '4: function $parcel$interopDefault(a) {',
```

**Comment by hand-dot** [comment]
@ddtbuilder Could you prepare a reproducible repository?
