### ISSUE TITLE
Make the icon not included in the template data

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#512]
### Is your feature request related to a problem? Please describe.

I'm considering making the icon's SVG data a root property of the plugin, as it feels unnatural to have it included in the template data.

Currently, the icon is set in the prop panel but is only used when rendering the left sidebar of the UI. When saving the template data, it becomes unnecessary data.

### Describe the solution you'd like

Move proppanel.defaultSchema.icon to Plugin.icon

### Describe alternatives you've considered

none

**Comment by peteward** [comment]
Agreed 👍 

We also `JSON.stringify()` the schema in the UI for change comparison so it is not efficient to have the icon in there
