### ISSUE TITLE
Playground update

### ISSUE THREAD

**Issue by romankolosok** [pdfme/pdfme#515]
### Describe the bug

I was trying to use the playground viewer and tried loading template with table which content is an array and got an error that content expects string. I used 4.1.0 version in code which worked with arrays but it's not working in playground.

### To Reproduce

get a template with table and replace content with [] instead of stringified array.
[template (18).json](https://github.com/user-attachments/files/16350188/template.18.json)

### Expected behavior

![image](https://github.com/user-attachments/assets/7bcb41f2-3052-4938-9d91-277fcf7a04c7)

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version: https://playground.pdfme.com/form-viewer
- Operating system: win 11
- Node.js version or Browser name & version: Microsoft Edge 126.0.2592.102
```

### Your Error Log

```shell
Expected string, received array
```

**Comment by hand-dot** [comment]
Updated. However, since the content is always a string, your error will not be resolved.

https://playground.pdfme.com/
