### ISSUE TITLE
Specify whether fields are required or optional within the schema

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#518]
### Is your feature request related to a problem? Please describe.

In our application, we want editors to be able to choose whether a field is required or not within their PDF designs.
Some fields/schemas are required, but some can be optional. In our example we're going to display a number of products, which might have a sale price and a normal price. The sale price will be optional. 

Recording the designer's intention of whether a field should be required allows other apps that provide data to pdfme for rendering to act accordingly, to ensure data is provided, or in our case choose a different design that satisfies the data requirements.

### Describe the solution you'd like

To mark a field as required/optional in the Designer. 

pdfme currently allows all fields to be optional by default (depending on how the schema pdf rendering function has been implemented). A schema that needs input but doesn't have it won't be rendered.

I propose making this `required` field optional on a schema, but if it exists we will check to ensure that the `inputs` passed to the renderer have data for all required fields.

In our case, we want `required = true` as default, but to be backwards compatible it should probably be `false` as default, but perhaps supporting an option that can be passed into the designer to reverse it. 

Fields would be rendered with a tickbox for required, set as above, and only included on schemas that are not read-only. It doesn't make sense for schemas such as read-only text, or shapes to be required. 

### Describe alternatives you've considered

This could be implemented outside of pdfme by the consuming application. 

However, we prefer the UX of a design dictating whether a field should be required or not.

**Comment by hand-dot** [comment]
@peteward 

So, does this mean that if a schema marked as required in the designer is passed to the generator without the necessary input, it will result in an error?

If that's the case, I think an approach that includes custom pre-processing in the generator to handle such errors would be a good solution.

**Comment by peteward** [comment]
Yes, that was the idea.

Do you have ideas about how a preprocessor would work?

**Comment by hand-dot** [comment]
Well, I don't have specific ideas, but I've been wanting to add pre-processing and post-processing for a while.

First, I'd like to consider the use cases and interfaces before implementation.
At this point, what we know is validation.

Also, we had something like this in the past, right?
REF: https://github.com/pdfme/pdfme/issues/391

Regarding post-processing, 
I think it would be good if we could add things like electronic signatures.

**Comment by peteward** [comment]
oh ok, so allow users to specify their own preprocessing rather than it being part of the core application? This is definitely a good idea.

I think in this case I'm more concerned with adding the capability to the designer rather than the generator, although I do think they work together.

I will work on a PR today and share what I was thinking, then you can tell me if you think it should be done differently
