### ISSUE TITLE
Adding auto page number to the bottom when adding new page

### ISSUE THREAD

**Issue by ghaith-arabkerly** [pdfme/pdfme#548]
### Is your feature request related to a problem? Please describe.

When trying to add a new page it would be better if there is a page number added at the bottom

### Describe the solution you'd like

I suggest making it as in option

### Describe alternatives you've considered

Manually adding pages number

### Additional context

And also it would be better to add duplicate page

**Comment by hand-dot** [comment]
Implemented by : https://github.com/pdfme/pdfme/pull/620

Docs: https://pdfme.com/docs/headers-and-footers
