### ISSUE TITLE
Field naming in a new page

### ISSUE THREAD

**Issue by ghaith-arabkerly** [pdfme/pdfme#549]
### Describe the bug

When adding new field in a new page the field's name is set to "field1" and if there is another field in a different page with the same name the content will be the same for both of them when generating the pdf even though I changed one of them

### To Reproduce

the playground pdfme code

### Expected behavior

making the new field's name unique across all pages

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version:
- Operating system:
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
no error log
```

**Comment by ghaith-arabkerly** [comment]
> ref: #528
mine is another problem , when creating a new page and adding a field it will be automatically named field1 and it won't be unique with another pages

**Comment by hand-dot** [comment]
I know this is not duplicate👍 I just set reference.

**Comment by peteward** [comment]
If the easiest solution is to ensure a unique default starting field name across pages then this is simple to implement.

**Comment by peteward** [comment]
It can be looked at together with https://github.com/pdfme/pdfme/issues/490.
