### ISSUE TITLE
display errors with subset fonts and text fields in Chrome

### ISSUE THREAD

**Issue by qtwf** [pdfme/pdfme#551]
### Describe the bug

On font embed without the subset option, the characters get displayed normally, although the look doesn't seem to resemble the font. However, the main issue is having to embed a large font to a PDF only to use a few characters, which can be resource intensive on the network.

On this case, the editable text fields can't seem to use the subset fonts properly when it comes to Chrome. In Firefox, this issue doesn't seem to be found.

In Chrome (with subset enabled):
![image](https://github.com/user-attachments/assets/e8ee7692-c0c7-4abe-8cfe-f53398771cae)

### To Reproduce

```ts

import {
  PDFDocument,
} from '@pdfme/pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import * as fs from 'fs';
import * as path from 'path';

const formPdfBytes = fs.readFileSync(path.resolve(`./src/forms/sample-form.pdf`));
const formPdfArrayBuffer = formPdfBytes.buffer.slice(formPdfBytes.byteOffset, formPdfBytes.byteOffset + formPdfBytes.byteLength);
const pdfDoc = await PDFDocument.load(formPdfArrayBuffer);
const form = pdfDoc.getForm();

const NotoSansCJKjp = fs.readFileSync(path.resolve('./src/assets/NotoSansCJKjp-Regular.otf'));
pdfDoc.registerFontkit(fontkit);
const jp_FontSupport = await pdfDoc.embedFont(NotoSansCJKjp, { subset: true });

const id = "<sample-id>"

const f = form.getTextField(id);
f.setText('mono物語gatari');
if (true) {
  f.updateAppearances(jp_FontSupport)
}

```

### Expected behavior

In Firefox (although it doesn't look like the embedded font):
![image](https://github.com/user-attachments/assets/4471efe1-39e1-4117-a59c-68753a88d57b)

In Chrome (with subset disabled):
![image](https://github.com/user-attachments/assets/9eda1cf5-407e-428b-bd73-f6533ede48e8)

### Your Environment

```markdown
- "@pdf-lib/fontkit": "1.1.1"
- "@pdfme/pdf-lib": "1.18.3"
- Operating system: Windows 10
- Node.js version or Browser name & version: nodejs v20.11
```

### Your Error Log

```shell
There is nothing to log
```

### Additional context

I could be wrong in coding. Please let me know if there's code that works better.

**Comment by hand-dot** [comment]
Hi @qtwf !

This issue should be in the following repository:
https://github.com/pdfme/pdf-lib/issues

Also, I'd like you to understand what subset fonts are before creating issues.
Based on my understanding, this is the correct behavior.
