### ISSUE TITLE
Unique field naming across different pages

### ISSUE THREAD

**Issue by ghaith-arabkerly** [pdfme/pdfme#558]
### Describe the bug

After the latest commit , the unique name validation works in only one page , if other page was added two fields with the same name can be added which would override the text

### To Reproduce

Generate a template and add a second page and try to create a new field with the same name as a field in the first page

### Expected behavior

Unique validation should work across all pages

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version:
- Operating system:
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
---
```

**Comment by peteward** [comment]
I cannot reproduce this in `main` (although there is a bug with the field number starting at 0 which I have fixed).

Here is what I see:

https://github.com/user-attachments/assets/f50762f4-3e82-4f9f-8b56-4af2b079460c

Can you share a video of your issue?

**Comment by ghaith-arabkerly** [comment]
My fault I think it's all good ! , when it's gonna be merged ?

**Comment by ghaith-arabkerly** [comment]
Uploading Screen Recording 2024-08-11 at 7.55.03 PM.mov…

**Comment by ghaith-arabkerly** [comment]
https://github.com/user-attachments/assets/f8462bbb-290c-4edc-be3c-9f3cdca2dd00

**Comment by ghaith-arabkerly** [comment]
My fault it's all good ! thank youuu
