### ISSUE TITLE
Right sidebar styling

### ISSUE THREAD

**Issue by ghaith-arabkerly** [pdfme/pdfme#561]
### Is your feature request related to a problem? Please describe.

Is there a way to change the styling of right sidebar buttons ? their wrapper div has no id or class so I can't reference it in css

### Describe the solution you'd like

adding a unique identifier like an id for each div

### Describe alternatives you've considered

overriding css but this results in overriding all buttons

**Comment by hand-dot** [comment]
Hey @ghaith-arabkerly 
we can use Custom UI.

Could you see this video and doc?
video: https://youtu.be/XQhVnhMB1nU?si=RGmneQdRBRQCyTmg
doc: https://pdfme.com/docs/custom-ui

**Comment by ghaith-arabkerly** [comment]
first of all , YOU'RE THE BEST !
I know I can use custom UI , I can customize global buttons and inputs , but no way for customizing the buttons only in the sidebar , or am I wrong ?
if no way is currently supported can I fork the repo and customize it freely ?
