### ISSUE TITLE
Transparency settings create error for HEX code

### ISSUE THREAD

**Issue by dkastl** [pdfme/pdfme#562]
### Describe the bug

When the color (text, border or background) gets set a transparency using the color selection widget, then the generated HEX code is not recognized as a valid value.

### To Reproduce

1. Got to https://pdfme.com/template-design
2. Add a text field for example
3. Select a text or background color
4. Set the transparency through the slider

### Expected behavior

Set the correct HEX code including transparency.
Eventually it's just the form validation not expecting transparency.

### Your Environment

```markdown
- The website's Template Design demo
```

### Your Error Log

```shell
See screenshot.
```

### Additional context

![Screenshot from 2024-08-12 12-39-19](https://github.com/user-attachments/assets/a6ae9bdd-496f-419c-871c-a56b2764f48d)

**Comment by peteward** [comment]
Transparency isn't valid in the hex when it comes to PDF generation for text, shapes and barcodes, you have to use opacity settings instead.

Maybe we can change the colour picker so that it doesn't offer transparency as an option 🤔

**Comment by dkastl** [comment]
I see. The following would change the validation to also accept transparency in `packages/common/src/helper.ts`:

```
export const isHexValid = (hex: string): boolean => {
  return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8}|[A-Fa-f0-9]{3}|[A-Fa-f0-9]{4})$/i.test(hex);
};
```

But if you say there is a problem with transparency support in generating PDF's, then I agree that removing the transparency slider might be the fastest solution.

**Comment by dkastl** [comment]
I thought Ant Design supports such an option in its `ColorPicker`, but PDFme uses `XRender`, which itself seems to implement https://www.npmjs.com/package/rc-color-picker

And while this library seems to provide a property [`disabledAlpha`](https://github.com/react-component/color-picker?tab=readme-ov-file#api), it doesn't seem to be made available htrough `XRender` ... unfortunately.

**Comment by peteward** [comment]
I think it might be a different component because the property is `enableAlpha` and I managed to hack it locally:

![Screenshot 2024-08-14 at 08 57 57](https://github.com/user-attachments/assets/732a8bd7-c1f1-4c8c-b3dd-
6377c4f87824)

I'll try to get a PR upstream to `form-render`

**Comment by hand-dot** [comment]
Wow Very nice

**Comment by peteward** [comment]
PR merged upstream in `form-render`, so I will try to upgrade once it is packaged. https://github.com/alibaba/x-render/pull/1545

However, there might be version conflicts with other packages as it is a significant upgrade.

**Comment by necessarylion** [comment]
Any update on this?

**Comment by peteward** [comment]
not yet. I need to find time to update the packages and check it

**Comment by peteward** [comment]
Looks like packages were already updated - [PR is up ](https://github.com/pdfme/pdfme/pull/653)

**Comment by necessarylion** [comment]
Just wondering, what if we extract opacity from hex code?

```
const hexString = '#6d1010B3'
const const alphaHex = hexString.slice(6, 8);
const opacity = parseInt('BF', 16) / 255;
```
Which I believe offers a better user experience.

**Comment by peteward** [comment]
What would the user experience be?

**Comment by peteward** [comment]
Oh, are you suggesting that we replace the existing opacity setting (below) and instead apply it on each element when rendering:

![Screenshot 2024-12-11 at 09 55 56](https://github.com/user-attachments/assets/be63a170-5a07-4b06-bf69-d35adf774d3b)

**Comment by necessarylion** [comment]
Yes. Something like that. But I believe it might be a lot of work to do.

**Comment by peteward** [comment]
Hmm yes it would need more thought. We have images and maybe other schemas that still need a separate opacity.

Whilst the change you suggest gives more fine-grained control over opacity of individual elements, the UX would then be inconsistent with some fields need an explicit opacity and some do it through colour.

It's an interesting idea, but needs more time. I think we should continue with the existing quick fix for the editor.
