### ISSUE TITLE
Using bwip-js on node.js

### ISSUE THREAD

**Issue by abdulgafur24** [pdfme/pdfme#57]
I guess you are using the browser version of `bwip-js` on the node.js version of your lib. Can you fix this?

**Comment by hand-dot** [comment]
@abdulgafur24 
Hi! thank you for posting.

> I guess you are using the browser version of bwip-js on the node.js version of your lib. Can you fix this?
It depends on the user's environment. 
if there is a window use the browser version of bwip-js

You can check below.
https://github.com/pdfme/pdfme/blob/main/packages/generator/src/helper.ts#L61

what problem do you have? please tell me

**Comment by abdulgafur24** [comment]
When I am trying to run build on `AWS lambda` it says `ReferenceError atob is not defined`. But after rebuilding this without `bwip-js` everything works fine

**Comment by hand-dot** [comment]
I see...
How about providing `atob` by building config?

example: 
https://github.com/pdfme/pdfme/blob/c587869d9207b017dd4518423cd91969ba7546d5/website/docusaurus.config.js#L90

If you can create a minimal reproduction environment, I'll check that.
