### ISSUE TITLE
Add Schema Radio button

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#570]
### Is your feature request related to a problem? Please describe.

Currently, for templates such as application forms, it is not possible to select from multiple options in a radio button-like format.

### Describe the solution you'd like

Add Radio button schema.

### Describe alternatives you've considered

Use Text for SVG schema.

---

ref: https://github.com/pdfme/pdfme/issues/457

**Comment by Meadril** [comment]
It would be very good if you could insert a field where you can switch between radio button and checkbox. At least that's how I did it in my project. 
I have also added a field called Group. All those with the same group are then regarded as a RadioGroup, for example.

**Comment by hand-dot** [comment]
working on it

**Comment by hand-dot** [comment]
Released as 5.2.2
