### ISSUE TITLE
Table overflows on text

### ISSUE THREAD

**Issue by ghaith-arabkerly** [pdfme/pdfme#576]
### Describe the bug

When a new row is added sometimes the elements beneath it gets pushed and sometimes now how to always ensure the elements are pushed ?

### To Reproduce

add a new table with new rows in a form sometimes overflows sometimes not

### Expected behavior

Table push the elements beneath it

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version:
- Operating system:
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
--
```

**Comment by hand-dot** [comment]
I think this is not issue, this is question. 
could you go to discussion?
