### ISSUE TITLE
Dynamic Table Schema shows weird behaviour when overflown

### ISSUE THREAD

**Issue by vikas-uptiq** [pdfme/pdfme#577]
### Describe the bug

Whenver we render table schema dynamically while generating the pdf, the fields/widgets below it gets cut off or unexpected white space gets added anywhere in the page sometimes... cutting off widgets below is most common attaching a video with playground running on localhost below tried with simple table and mocking dynamic data in it

[Kazam_screencast_00001.webm](https://github.com/user-attachments/assets/f76fe64a-cd15-4afd-969b-892854548740)

### To Reproduce

Just do the steps shown in the video uploaded and mock long length data in table while generating pdf. place some widgets below table 

### Expected behavior

Ideally table should just adapt to height of the data provided and just move other widgets below it by additional or less offset height nothing more.. i.e if my below widget is 20mm below table then it should be exact 20mm below if overflown table end on same page and below widget height can fit . else below widgets should start with padding top of page as y position on next page

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):4.3.2
- pdfme version: 4
- Operating system: Linux
- Node.js version or Browser name & version: 18.19.0
```

### Your Error Log

```shell
no error log
```

### Additional context
```
const generateTableData = (rows: number, cols: number) => {
  const data = [];
  for (let i = 0; i < rows; i++) {
    const row = [];
    for (let j = 0; j < cols; j++) {
      row.push(`Row ${i} Col ${j}`);
    }
    data.push(row);
  }
  return data;
};

export const generatePDF = async (currentRef: Designer | Form | Viewer | null) => {
  if (!currentRef) return;
  const template = currentRef.getTemplate();

  // --updated part to mock table data
  // updating the table schema content just to mock dynamic table data
  for (const pageSchemas of template.schemas) {
    for (const key in pageSchemas) {
      const schema = pageSchemas[key];
      if (schema.type === 'table') {
        schema.content = JSON.stringify(generateTableData(40, 3));
      }
    }
  }
  // mocking end

  const inputs =
    typeof (currentRef as Viewer | Form).getInputs === 'function'
      ? (currentRef as Viewer | Form).getInputs()
      : getInputFromTemplate(template);
  const font = await getFontsData();

  try {
    const pdf = await generate({
      template,
      inputs,
      options: {
        font,
        title: 'pdfme',
      },
      plugins: getPlugins(),
    });

    const blob = new Blob([pdf.buffer], { type: 'application/pdf' });
    window.open(URL.createObjectURL(blob));
  } catch (e) {
    alert(e + '\n\nCheck the console for full stack trace');
    throw e;
  }
};
```

above is just updated code to mock table data while doing generate pdf

**Comment by hand-dot** [comment]
same: https://github.com/pdfme/pdfme/issues/429
