### ISSUE TITLE
Removed "Columns" property from Template should be brought back..

### ISSUE THREAD

**Issue by vikas-uptiq** [pdfme/pdfme#578]
### Is your feature request related to a problem? Please describe.

Earlier before version 4 we used to have columns in template which was a array of keys of field names in the sequence which was showing the z-axis-order of fields . i.e which is below or above with respect to other fields lying in same region.
But now in version 4 we have remove this so there is no way of knowing this exact sequence of field along z-axis. We can do Object.keys on schams but in javascript key order is not ensured and is difficult to maintain when we do some operations on template .. so we need this back or atleas @hand-dot please provide alternative but reliable solution for this

### Describe the solution you'd like

Column property should come back ot we should convert page wise schema object  to page wise schema array so array will always ensure correct order of fields.

### Describe alternatives you've considered

Mentioned in description

### Additional context

This is useful in one of the project i am working on in which i have to adjust the text colors in actually rendered pdf on the basis of its contrast with background so it becomes important to know what widget / field is behind the text to know the actual background color of text based.. and then by knowing it ... calculating contrast of text color and background widget bg color becomes easy

**Comment by hand-dot** [comment]
Since ECMAScript 2015 (ES6), it's not an issue.

**Comment by vikas-uptiq** [comment]
> Since ECMAScript 2015 (ES6), it's not an issue.

@hand-dot Actually i am trying to say when we try to modify or process templete before goes to generator. It breaks the sequence of fields and its not that possible to maintain the object correctly while modifying it 

I was modifying it for table dynamic stuff and other theme related changes

**Comment by hand-dot** [comment]
The order is reflected in methods such as `Object.keys()`, `Object.values()`, `Object.entries()`, and `for...in` loops.

This translation accurately conveys the original Japanese statement, which explains that the order of object keys is maintained when using these specific JavaScript methods and loop constructs.

**Comment by vpn-dev** [comment]
> The order is reflected in methods such as `Object.keys()`, `Object.values()`, `Object.entries()`, and `for...in` loops.

Ok so i will just store that order on my side before any modification thanks.. :+1:
