### ISSUE TITLE
Dynamic font size

### ISSUE THREAD

**Issue by hand-dot** [pdfme/pdfme#58]
ref 
- https://pdf-lib.js.org/docs/api/classes/pdffont#widthoftextatsize
- https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript
- https://github.com/rikschennink/fitty

**Comment by steffancarrington** [comment]
Hey @hand-dot, 

I'm looking to implement this in our app setup, and I was just wondering what approach you were thinking of taking to implement this functionality? 

Thanks

**Comment by hand-dot** [comment]
ref: https://github.com/pdfme/pdfme/pull/165
