### ISSUE TITLE
Schema JSON structure relies on key order which is not guaranteed by the JSON spec

### ISSUE THREAD

**Issue by peteward** [pdfme/pdfme#584]
### Is your feature request related to a problem? Please describe.

JSON is an interchange format that does not guarantee key ordering in other languages.
pdfme relies on the ordering of it's keys to dictate the order in which they are displayed and rendered. 

If you export a schema from pdfme and transfer it to another JSON storage medium, such as a MySQL JSON field, this ordering will be lost. 

In our case, when schemas are reloaded from storage they have lost the intended order.

### Describe the solution you'd like

I think we should consider changing the schema structure.  Instead of having the schema items as keys, we can use an array where the `key` is part of each object:

BEFORE:
```
{
    "field1": {
      "type": "text",
      "content": "Field 1",
      "width":45,
      "height":10
    },
    "field2": {
      "type": "text",
      "content": "Field 2",
      "width":45,
      "height":10
    }
}
```

AFTER:
```
[
    {
      "name": "field1",
      "type": "text",
      "content": "Field 1",
      "width":45,
      "height":10
    },
    {
      "name": "field2",
      "type": "text",
      "content": "Field 2",
      "width":45,
      "height":10
    }
]
```

For the multi-page structure this would mean an array of arrays, or we could consider adding a `page` attribute.

I am aware that this is a very big BC break. To offset this, I suggest that we support a schema migration on load that would convert any schema from a template < v5 to the new format, and this could be used in all tools. 

### Describe alternatives you've considered

We could keep the schema format unchanged, but store the `order` separate on the template as an array of keys. This would mean the schema format doesn't suffer from a BC break, but would make the code more complex and not resolve the underlying issue. Users would need to save the `order` along with the `schema`.

We could do nothing, and accept this limitation and ask users to workaround it (store objects as serialised strings rather than JSON), but this doesn't feel great.

### Additional context

I would be happy to attempt this work if we thought it was the right approach.

**Comment by peteward** [comment]
ref: https://github.com/pdfme/pdfme/issues/490

**Comment by hand-dot** [comment]
Thank you for raising this issue.

I think this is better than the previous approach of storing the order in 'columns' (which was probably similar to the 'order' approach you suggested), which we had removed in the past. Removing the 'columns' code made our codebase cleaner, but there was a trade-off aspect to it.

Basically, I agree with this approach.

To avoid unnecessary conflicts, I'd like to let you know that I'm currently implementing [bug fixes for the table feature](https://github.com/pdfme/pdfme/pull/574), so if possible, I'd prefer to merge your PR after those fixes have been merged.

The table bug fixes should be completed within this month.

**Comment by peteward** [comment]
Thanks @hand-dot.

I will start work on this then wait for your changes to rebase onto 👍

**Comment by hand-dot** [comment]
@peteward 
Excellent. This format is more correct as template data. Thank you.
You can merge this into the main branch at any time.

This PR changes the data structure, so we'll likely need to bump up the major version.

However, users won't need to change their code because the migration process runs after the template is input.
We'll make sure to highlight this point in the release notes.

Regarding the V5 release, I have a few things I want to do, such as removing readOnlyText and tableBeta. 
I plan to release it soon, but only after these tasks are completed.

**Comment by peteward** [comment]
implemented

**Comment by kaioenzo** [comment]
Why not just put a number in properties and order the template when reading in UI or when generating the PDF? I think that using named properties is much more readable and intuitive than using arrays to inputs.

**Comment by peteward** [comment]
Do you mean it's easier to determine what the inputs should be from the schema as an array structure?

I agree this is _slightly_ more complex now, but it's the difference between extracting a `name` key from each array element versus getting object keys, which is not difficult.

We could have implemented an attribute to determine the order of elements, but this would have been more complex for pdfme internally to maintain. I would also argue that readability can be worse if you work with storage mediums that change the order of keys (which MySQL JSON data type does for example). If you are trying to visually compare 2 schemas where the keys have been reordered it's much harder.

Your suggestion is not a bad one, but I don't think it's better, and the implementation has been completed now.
