### ISSUE TITLE
ReferenceError: atob is not defined

### ISSUE THREAD

**Issue by MigueloAtla** [pdfme/pdfme#59]
Not able to use the package.
I'm getting this error only importing from @pdfme/generator.

**Comment by hand-dot** [comment]
Hi @MigueloAtla 

Please check https://github.com/pdfme/pdfme/issues/57#issuecomment-1079838308

If you can create a minimal reproduction environment, I'll check that.

**Comment by HaeusslerAdrian** [comment]
Hi @hand-dot,

I have the same issue and I created the minimal app
https://github.com/adresta/pdfme_issue

I also found out that this issue exists on node14, but it will go away when upgrading to node16

**Comment by hand-dot** [comment]
@HaeusslerAdrian 

Thank you create a minimal app, I'll check that repo.

**Comment by hand-dot** [comment]
ref https://symfoware.blog.fc2.com/blog-entry-2596.html
