### ISSUE TITLE
Custom Panels and Additional Shapes in PDFme

### ISSUE THREAD

**Issue by Brijesh-Baxani** [pdfme/pdfme#598]
### Is your feature request related to a problem? Please describe.

Currently, PDFme provides limited flexibility with its UI customization options, specifically with the left and right panels that contain standard controls. Additionally, the shape options are limited to basic geometries such as rectangles and ellipses. This limitation poses a challenge for applications that require a more personalized user interface and advanced design elements, making it difficult to achieve a tailored and attractive UI for end-users.

### Describe the solution you'd like

1. Custom Panels:

- I would like the ability to remove the existing left and right panels in the PDFme UI and replace them with custom panels that allow for the integration of user-defined controls and UI components.
- This feature would enable developers to design a more customized interface that suits specific application needs, enhancing the overall user experience and aligning with unique project requirements.

2. Additional Shapes:

- Extend the shape options available in PDFme to include additional geometries such as hexagons, stars, and other custom shapes.
- This can be implemented by expanding the current shape rendering functions within the library, allowing for a broader range of design possibilities when creating templates.

### Describe alternatives you've considered

- Using CSS and JavaScript Workarounds: Initially, I considered hiding the default panels using CSS and injecting custom JavaScript to replace them with my custom panels. However, this approach is not ideal as it results in maintenance challenges and potential conflicts with future updates of the library.
- Forking the Repository: Another alternative considered was forking the PDFme repository to implement these changes independently. While feasible, this approach would require significant ongoing effort to keep the fork updated with upstream changes, which may not be sustainable in the long run.

### Additional context

Integrating these features directly into PDFme would not only solve the immediate need for more customization but also add value to the tool for other developers facing similar challenges. By allowing greater flexibility in UI design and shape options, PDFme could cater to a wider range of use cases and applications, enhancing its appeal as a versatile document creation tool.

I am open to contributing to the implementation of these features and would appreciate guidance on the best approach if this request aligns with your development roadmap.

Thank you for considering this feature request.

**Comment by nonubot123** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by hand-dot** [comment]
You can achieve by plugin

https://pdfme.com/docs/custom-schemas
