### ISSUE TITLE
Japanese characters can not be shown correctly in playground app

### ISSUE THREAD

**Issue by scobin** [pdfme/pdfme#60]
Hi, I tried the playground app and change "Pet Name" to "犬の写真".
After I click the "Generate PDF" button, Japanese characters are shown as  □□□□.

Do I miss something or is it need some settings to show Japanese characters?

**Comment by hand-dot** [comment]
Hi @scobin 
Please check [this link](https://pdfme.com/docs/guides/custom-font).

**Comment by scobin** [comment]
Hi, @hand-dot 
Thank you for the link.
I solved it.
