### ISSUE TITLE
value.split is not a function at splitTextToSize

### ISSUE THREAD

**Issue by ivanbogdan-git** [pdfme/pdfme#609]
### Describe the bug

Hi, this is my first time opening a GitHub issue, so please pardon me if I don't get everything right.
I'm having issue generating a PDF with a working template:
[template.json](https://github.com/user-attachments/files/17309464/template.json)

```ts
import type { Template } from '@pdfme/common';
import { barcodes, image, text } from '@pdfme/schemas';
import { generate } from '@pdfme/generator';
import { basePdf, schemas } from './template';

export const generatePdf = async (inputs: Record<string, string>[]) => {
  const plugins = { text, image, qrcode: barcodes.qrcode };
  const template: Template = {
    basePdf,
    schemas,
    pdfmeVersion: '5.0.0',
  }

  try {
    const pdf = await generate({
      template,
      plugins,
      inputs: [
        {
          "ticket_purchase_id": 216,
          "ticket_purchase_created_at": "2024-10-09T02:42:09.350875+00:00",
          "ticket_purchase_numbering": "ticket_purchase.numbering",
          "qrcode": "http://localhost:3000/api/tickets/authorize?c=undefined&i=216",
          "event_venue_title": "event.venue_title",
          "event_venue_address": "event.venue_address",
          "event_venue_postal_code": "event.venue_postal_code",
          "event_venue_city": "event.venue_city",
          "ticket_type_day": "ticket_type.day",
          "ticket_type_date": "ticket_type.date",
          "ticket_type_time": "ticket_type.time",
          "ticket_type_title": "ticket_type.title",
          "ticket_type_price": "ticket_type.price",
          "event_title": "event.title",
          "customer_details_full_name": "Ivan Bogdan",
          "customer_details_email": "email",
          "customer_details_address": "address,
          "event_organiser_title": "event.organiser_title",
          "event_organiser_address": "event.organiser_address",
          "event_organiser_postal_city_country": "undefined undefined undefined",
          "customer_details_postal_city_country": "address",
          "customer_details_phone": "1234",
          "event_organiser_oib": "event.organiser_oib"
        }
      ]
    });
    return { data: Buffer.from(pdf), error: null };
  } catch (error) {
    console.error('Error generating PDF:', error);
    return { data: template, error: (error as Error).message };
  }
};
```

### To Reproduce

The uploaded template can be loaded within PDFMe template designer https://pdfme.com/template-design. 

Reproducing should be quite straightforward. Let me know if you need a minimal reproduction example and I'll create it.

### Expected behavior

PDF should be generated as expected. 

### Your Environment

```markdown
- pdfme versions
    "@pdfme/common": "^5.0.0",
    "@pdfme/generator": "^5.0.0",
    "@pdfme/schemas": "^5.0.0",
- Operating system: MacOS
- Node.js version or Browser name & version
    "node": ">=18.17.0"
```

### Your Error Log

```shell
TypeError: value.split is not a function at splitTextToSize (/Users/ivanbogdan/upad/.next/server/chunks/297f2_@pdfme_schemas_dist_esm_src_3f9323._.js:321:11) at pdfRender (/Users/ivanbogdan/upad/.next/server/chunks/297f2_@pdfme_schemas_dist_esm_src_3f9323._.js:2593:429) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async generate (/Users/ivanbogdan/upad/.next/server/chunks/node_modules__pnpm_5dfa62._.js:8941:17) at async generatePdf (/Users/ivanbogdan/upad/.next/server/chunks/src_c9e70c._.js:598:21)
```

**Comment by peteward** [comment]
Hi!

You might get that error if an input you are passing is not a string. 
What happens if you change this:
```
        "ticket_purchase_id": 216,
```
to:
```
        "ticket_purchase_id": "216",
```

If this doesn't help, could you try reducing the inputs until you find out which is the problem?

**Comment by ivanbogdan-git** [comment]
> Hi!
> 
> You might get that error if an input you are passing is not a string. What happens if you change this:
> 
> ```
>         "ticket_purchase_id": 216,
> ```
> 
> to:
> 
> ```
>         "ticket_purchase_id": "216",
> ```
> 
> If this doesn't help, could you try reducing the inputs until you find out which is the problem?

I just figured that a minute ago, and was about to close this. 

Wonderful, I really appreciate your help anyways!

**Comment by ivanbogdan-git** [comment]
> Hi!
> 
> You might get that error if an input you are passing is not a string. What happens if you change this:
> 
> ```
>         "ticket_purchase_id": 216,
> ```
> 
> to:
> 
> ```
>         "ticket_purchase_id": "216",
> ```
> 
> If this doesn't help, could you try reducing the inputs until you find out which is the problem?

I just figured that a minute ago, and was about to close this. 

Wonderful, I really appreciate your help anyways!
