### ISSUE TITLE
Designer page is missing when using object as basePdf

### ISSUE THREAD

**Issue by sschimmel** [pdfme/pdfme#619]
### Describe the bug

When I render the Designer with an object with width, height and padding the designer doesn't render the page. If I use the BLANK_PDF from @pdfme/common the designer does render the page and I can drag and drop fields to it.

Designer:
![image](https://github.com/user-attachments/assets/ae2c4993-2e55-4c23-9b22-853585c4edad)

### To Reproduce

Create a new designer with the following template:

```
const pdfTemplate: Template = {
  basePdf: { 
    width: 210, 
    height: 297,
    padding: [20,20,20,20] 
  },
  schemas: [],
}
```

### Expected behavior

The designer renders with a blank page in A4 size with landscape orientation based on the provided template basePdf.

### Your Environment

```markdown
"@pdfme/common": "^5.1.6",
"@pdfme/generator": "^5.1.6",
"@pdfme/schemas": "^5.1.6",
"@pdfme/ui": "^5.1.6",

- Operating system: macOS 15.0.1 
- Node.js version or Browser name & version: Chrome 130.0.6723.91

The designer is included in a React application
```

### Your Error Log

```shell
There are no errors in the console
```

**Comment by hand-dot** [comment]
```
const pdfTemplate: Template = {
  basePdf: { 
    width: 210, 
    height: 297,
    padding: [20,20,20,20] 
  },
  schemas: [{}],
}
```
