### ISSUE TITLE
Detection of Vulnerabilities in pdfjs-dist

### ISSUE THREAD

**Issue by tkosushi** [pdfme/pdfme#625]
### Is your feature request related to a problem? Please describe.

The `pdfme/ui` package includes a version of `pdfjs-dist` that contains vulnerabilities as described in the following link:
https://github.com/mozilla/pdf.js/security/advisories/GHSA-wgrm-67xf-hhpq

Our project has detected security alerts due to these vulnerabilities.

### Describe the solution you'd like

Are there any plans to update the version of `pdfjs-dist` to address these vulnerabilities?
Alternatively, can the vulnerabilities be mitigated by setting the `isEvalSupported` option to `false` as described in the workaround? 
Or, have these vulnerabilities already been resolved by other means?

### Describe alternatives you've considered

If the above issue has already been resolved, we will ignore the security alerts related to this vulnerability.

### Additional context

ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1893645

**Comment by hand-dot** [comment]
on it.

**Comment by hand-dot** [comment]
Fixed by this commit: https://github.com/pdfme/pdfme/commit/4fc737f313b1d301f253c4aa02616b09421e874f
And Released as 5.1.7
