### ISSUE TITLE
TypeError: e.charCodeAt is not a function

### ISSUE THREAD

**Issue by abdulgafur24** [pdfme/pdfme#64]
If I use node js 16 everything is ok, but if I switch to node js 14 there is this error:

```javascript
TypeError: e.charCodeAt is not a function
    at h (/project/node_modules/@pdfme/generator/dist/index.js:2:785405)
    at Object.loadFont (/project/node_modules/@pdfme/generator/dist/index.js:2:770307)
    at Object.r (/project/node_modules/@pdfme/generator/dist/index.js:2:785615)
    at Object.8887 (/project/node_modules/@pdfme/generator/dist/index.js:2:823962)
    at t (/project/node_modules/@pdfme/generator/dist/index.js:2:2196075)
    at /project/node_modules/@pdfme/generator/dist/index.js:2:3155012
    at /project/node_modules/@pdfme/generator/dist/index.js:2:3161603
    at /project/node_modules/@pdfme/generator/dist/index.js:2:3161609
    at /project/node_modules/@pdfme/generator/dist/index.js:2:84
    at Object.<anonymous> (/project/node_modules/@pdfme/generator/dist/index.js:2:223)
```

**Comment by hand-dot** [comment]
@abdulgafur24 Thank you bug report. I'll check this problem.

**Comment by abdulgafur24** [comment]
any news?

**Comment by hand-dot** [comment]
@abdulgafur24 
Sorry, for the late reply.

I reproduced this bug, and it comes from https://github.com/metafloor/bwip-js code that is used in https://github.com/pdfme/pdfme/blob/main/packages/generator/src/helper.ts#L42
honestly, I don't know how to fix this...

and we have [another problem](https://github.com/pdfme/pdfme/issues/59#issuecomment-1102751798) when using node v14.
node v14 is not an LTS version, So I'm considering to be node v14 unsupported version in pdfme in the future.

Do you need using in node v14?

**Comment by abdulgafur24** [comment]
I thought aws lambda doesn't support node.js version 16. But now I see that it supports, so the question disappears.

**Comment by hand-dot** [comment]
Fixed by https://github.com/pdfme/pdfme/commit/1979649a61b68119404ffe64c25c509bb7773a16
