### ISSUE TITLE
How to use PDFME with customization and need to maintain it in separate repo and use it?

### ISSUE THREAD

**Issue by ramsmart-inno** [pdfme/pdfme#644]
### Describe the bug

I tried the separate repo approach, but It says "Cannot find module '@pdfme/common' or its corresponding type declarations." & it has in node_modules folders.

<img width="1694" alt="Screenshot 2024-11-24 at 8 39 30 AM" src="https://github.com/user-attachments/assets/81642879-177c-4a71-adf7-a51054d0115f">

Need support & suggest to use this approach for customization.

### To Reproduce

Hosted the PDFME in separate repo and use it.
<img width="1396" alt="Screenshot 2024-11-24 at 11 13 09 AM" src="https://github.com/user-attachments/assets/b16c8605-0f2c-4547-a7d4-af6c216e5254">

### Expected behavior

Able to run with customized package repo.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): Both
- pdfme version: 3.4.1
- Operating system: MacOS
- Node.js version or Browser name & version: 18
```

### Your Error Log

```shell
Compiled with problems:
×
ERROR in ./src/App.tsx 7:0-41
Module not found: Error: Can't resolve '@pdfme/common' in '/Users/rammohan/Desktop/NewBeginnings2024/myapp/src'
ERROR
[eslint] EACCES: permission denied, mkdir '/Users/rammohan/Desktop/NewBeginnings2024/myapp/node_modules/.cache'
ERROR in src/App.tsx:3:26
TS2307: Cannot find module '@pdfme/common' or its corresponding type declarations.
    1 | import React, { useEffect, useRef, useState } from 'react';
    2 | import './App.css';
  > 3 | import { Designer } from '@pdfme/common';
      |                          ^^^^^^^^^^^^^^^
    4 | import type { Template } from '@pdfme/common';
    5 |
    6 |
ERROR in src/App.tsx:4:31
TS2307: Cannot find module '@pdfme/common' or its corresponding type declarations.
    2 | import './App.css';
    3 | import { Designer } from '@pdfme/common';
  > 4 | import type { Template } from '@pdfme/common';
      |                               ^^^^^^^^^^^^^^^
    5 |
    6 |
    7 | function App() {
```

**Comment by hand-dot** [comment]
I'm not entirely sure, but is this a bug? 
Since it duplicates the following, I'll close it. Please await a response on the discussion page.  

https://github.com/pdfme/pdfme/discussions/643
