### ISSUE TITLE
Multi Page PDF as basePDF

### ISSUE THREAD

**Issue by karo-init** [pdfme/pdfme#65]
Hi Kyohei, at first thanks for the great repository ! I'm still on the "Getting started level" with it and I tried to use a self created Multipage PDF as basePDF but I had only success with a Single Page PDF. Do I have to use an additional property for using a Multipage PDF as basePDF or is it not possible yet ?

**Comment by hand-dot** [comment]
Hi @karo-init !

We can use Multipage PDF as basePDF.
Could you please share minimal reproduction and code?

**Comment by hand-dot** [comment]
@karo-init 

Sorry for the late reply.
Could you upload EXAMPLE_PDF?

**Comment by hand-dot** [comment]
@karo-init 
I labeled the answer because I did not receive a reply.
If there are no replies at this point, it will be closed after 30 days.
If you have any questions, please comment.
