### ISSUE TITLE
issue with select schema

### ISSUE THREAD

**Issue by minh-tranchi** [pdfme/pdfme#650]
### Describe the bug

.

### To Reproduce

.

### Expected behavior

.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui):
- pdfme version: 5.2.8
- Operating system:
- Node.js version or Browser name & version:
```

### Your Error Log

```shell
.
```

### Additional context

Case 1:
Bug: The `select` only has 1 option -> That option can't be selected
Step to reproduce: Create a `select` with 1 option -> Go to Form and try to select that option -> That option can't be selected
Expected: Can still select that Option

Case 2:
Bug: The `input` value for a select field is mismatch the options
Step to reproduce: Go to Form and select an option -> Go to Edit and delete that option -> Go back to Form and still see that option
Expected: That `select` field should be cleared

**Comment by hand-dot** [comment]
Can we close this?
