### ISSUE TITLE
Table Field Glitch and Page Break Issues When Adding Rows to the Table in Custom PDF

### ISSUE THREAD

**Issue by vuram-swat** [pdfme/pdfme#657]
### Describe the bug

When a custom PDF is loaded into the form, and it contains a table field, the following issues occur:

- Adding new rows to the table does not move other fields below it, causing the layout to break. This behavior is different from when a blank PDF is used, where the table expansion works as expected.
- The page break functionality does not work properly when a custom PDF with a table field is loaded. The page break works fine with a blank PDF, but when the custom PDF is used, it fails to trigger appropriately.
- A small visual glitch occurs when adding new rows to the table in the custom PDF, impacting the user experience.

[Recording-20241212_102757.webm](https://github.com/user-attachments/assets/725d65f7-591c-49ff-b95c-b44be87681f8)

### To Reproduce

- Load a custom PDF with a table field into the form.
- Try adding rows to the table.

### Expected behavior

- When a new row is added, other fields should move down accordingly.
- Page breaks should work properly, even when a custom PDF is used.
- No glitches should occur when adding new rows to the table field.

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): @pdfme/ui
- pdfme version: 5.2.8
- Operating system: Windows 10
- Node.js version or Browser name & version: Microsoft Edge Version 131.0.2903.86
```

### Your Error Log

```shell
-
```

**Comment by hand-dot** [comment]
> To support page breaks, ensure to set the basePdf property in the template to { width: number, height: number, padding: [number,number,number,number] }.


ref: https://pdfme.com/docs/tables#using-the-table-schema
