### ISSUE TITLE
Unknown font format

### ISSUE THREAD

**Issue by nitishpratap18** [pdfme/pdfme#658]
### Describe the bug

Getting Unknown font format while generating pdf from node.js. It was generated yesterday.
I have 2 environments stag and prod. I was testing on stag so i build that i do npm i and this leads to download new version.
On production we have older one so it was working.

### To Reproduce

try {
        console.log("inputs are ::::::",inputs);
        console.log("template is ::::::",template);
        let pdf =   await generate({template, inputs,plugins: getPlugins()})
        // res.set('Content-Type', 'application/pdf');
        const pdfBase64 = Buffer.from(pdf).toString('base64'); // Convert PDF buffer to base64
        // const newPdf = await processPdfBase64(pdfBase64);
        // res.set('Content-Disposition', `attachment; filename=${pdfName}.pdf`);
        // fs.writeFileSync(path.join(__dirname, `test.pdf`), pdf);
        // res.set('Content-Length', pdf.length);
        // Send the PDF as the response
        // res.end(pdf);
        res.json({
            filename: `${pdfName}.pdf`,
            base64: pdfBase64
        });
    }catch (err){
        req.log.info("Error generating PDF:", err);
        res.status(500).send('Error generating PDF',err.message);
    }

### Expected behavior

PDF must be generated.

### Your Environment

```markdown
"@pdfme/common": "^3.4.3",
    "@pdfme/generator": "^3.4.3",
    "@pdfme/schemas": "^3.4.3",
    "@pdfme/ui": "^5.1.5",
- Operating system: 
- Node.js version or Browser name & version:  node:current-alpine
```

### Your Error Log

```shell
gm566","pid":1,"req_id":"49c6355d-a58b-4a05-b77b-9b2666a0ff90","level":30,"msg":"Error generating PDF: Error: Unknown font format\n    at Object.$59aa4ed98453e1d4$export$185802fd694ee1f5 (/usr/src/app/node_modules/fontkit/dist/main.cjs:60:11)\n    at getFontKitFont (/usr/src/app/node_modules/@pdfme/schemas/dist/cjs/src/text/helper.js:105:33)\n    at pdfRender (/usr/src/app/node_modules/@pdfme/schemas/dist/cjs/src/text/pdfRender.js:47:40)\n    at generate (/usr/src/app/node_modules/@pdfme/generator/dist/cjs/src/generate.js:61:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Object.downloadPdf (/usr/src/app/helper/submission.js:222:21)\n    at async downloadPdf
```

**Comment by peteward** [comment]
It appears that fontkit does not like your font file.

Can you share the font file that you are using? What format is it? OTF? TTF?

**Comment by nitishpratap18** [comment]
Not using Any file. It is coming due to `FROM node:current-alpine` in my docker file and it is installing updated alpine version.
Fixed when i used `FROM node:20-alpine3.17` in my docker file
