### ISSUE TITLE
Adding URL in PDF

### ISSUE THREAD

**Issue by HammadBukhari** [pdfme/pdfme#73]
Thanks for the great plugin. 
Can I add a clickable URL to the PDF using this? I looked into the available types and couldn't find it.

**Comment by hand-dot** [comment]
@HammadBukhari 
Thank you for using pdfme.
Sorry, it is not possible to set a URL to a PDF at the moment.

**Comment by HammadBukhari** [comment]
Thanks for letting me know. btw awesome plugin.

**Comment by LeBovin** [comment]
@hand-dot Hello,
Have you any idea how to do it? I need this feature and I'm up to submit a PR for this. Unfortunately I don't have much experience with PDF so if you have some hints it would save me some time

**Comment by karstenwinter** [comment]
i noticed that email@adress.es are automatically turned into links

and that https://... text is clickable :)

Seems solved I guess

a link element that has different display text than url content would be interesting but is currently not needed (it would be a nice to have)
