### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by tudorels** [pdfme/pdfme#74]
Hi, first of all I want to congratulate you for this initiative, there is a need for such a tool.
And I want to ask you if it is possible to use fontWeight for dynamic text fields and maybe more css attributes?
Thanks!

**Comment by hand-dot** [comment]
Hi @tudorels 

> it is possible to use fontWeight for dynamic text fields and maybe more css attributes?
We can't use font-weight. but we can load and use a bold font as the custom font. (https://pdfme.com/docs/guides/custom-font)
also, we can't use CSS attributes.
I want to know what purpose to use CSS attributes.

Thanks!

**Comment by tudorels** [comment]
Like border, padding. Also the ability to insert tables and format them using css. Thanks!
