### ISSUE TITLE
What type exactly supports the Input of Image Schema??

### ISSUE THREAD

**Issue by pmw1407** [pdfme/pdfme#80]
Hi, I'm currently trying to put images into my base pdf.

I put my images from my local computer and convert them into base64 string and it works well.

But when I try to put images downloaded from the Amazon S3 storage, it doesn't work well.

I think the reason it doesn't work is that the content-type of images downloaded from S3 is ```octet-stream```.

I tried to convert content-type of these images into ```image/jpeg``` or something, it shows just blank.

Is it correct that pdfme doesn't support ```application/octet-stream;base64``` string and only supports ```image;base64``` string?

**Comment by anthlasserre** [comment]
Hey @pmw1407 I met some issues to display correctly my input images.
I managed to get a rid of it like this.

Here is my fetcher.
```typescript
export const fetchImage = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const buffer = await response.buffer();
    return buffer.toString("base64");
  } catch (error) {
    console.error(error);
  }
};
```

And here is when I generate it:
```typescript
const image = await fetchImage(IMAGE_URL);
const pdf = await generate({
    template,
    inputs: {
        image1: `data:image/png;base64,${YOUR_BASE64_STRING}`
    },
    options: { font: fonts },
  });
```

**Comment by anthlasserre** [comment]
Hey @pmw1407 I met some issues to display correctly my input images.
I managed to get a rid of it like this.

Here is my fetcher.
```typescript
export const fetchImage = async (url: string): Promise<string> => {
  try {
    const response = await fetch(url);
    const buffer = await response.buffer();
    return buffer.toString("base64");
  } catch (error) {
    console.error(error);
  }
};
```

And here is when I generate it:
```typescript
const image = await fetchImage(IMAGE_URL);
const pdf = await generate({
    template,
    inputs: {
        image1: `data:image/png;base64,${YOUR_BASE64_STRING}`
    },
    options: { font: fonts },
  });
```

**Comment by pmw1407** [comment]
Thanks bro I'll try this!!
