### ISSUE TITLE
What is the purpose of columns in Template? 

### ISSUE THREAD

**Issue by devcloser** [pdfme/pdfme#82]
Hi, 

Do we need to add columns to Template?

For example
```json
const template: Template = {
    basePdf: BLANK_PDF,
    schemas: [],
    columns: []
}
```

Not sure what is the purpose of columns here. I could not find any explanation on the document.

**Comment by hand-dot** [comment]
Hi @devcloser 

columns are used by form's focus order.

![CleanShot20220711at164216](https://user-images.githubusercontent.com/24843808/178213654-bcb684f5-6a5e-4b0d-91cf-e7550b98de7d.gif)

therefore, if you need a generator only, you don't need columns.

**Comment by hand-dot** [comment]
@devcloser 

I labeled the answer because I did not receive a reply.
If there are no replies at this point, it will be closed after 30 days.
If you have any questions, please comment.
