### ISSUE TITLE
Designer UI's size is buggy

### ISSUE THREAD

**Issue by bcdrme** [pdfme/pdfme#90]
I've noticed that many `div` inside the Designer component have their `height` and `width` computed in typescript instead of using CSS. I'm not sure why this is the case, their might be a good reason for that ?

It causes many issues when trying to integrate the Designer inside an existing app, it overflows everywhere. I think it's because it doesn't react well to viewport size change. The core issue is that height and width are computed instead of using css flex etc... 

The problem is visible in the official codesandbox example integration with React
https://codesandbox.io/embed/github/pdfme/pdfme-playground/tree/main/?module=%2Fsrc%2FDesigner.tsx

![image](https://user-images.githubusercontent.com/54471255/182649279-2637ea67-d4db-4d0c-9edb-5312c06a3189.png)

In the current state, it's almost impossible to integrate the Designer anywhere, which is a real shame ! 😢 

Many thanks for this lib by the way !

**Comment by hand-dot** [comment]
Hi @bcdrme 

I checked codesandbox demo.
but I can't see the overflow problem...

<img width="1470" alt="CleanShot 2022-10-15 at 16 23 52@2x" src="https://user-images.githubusercontent.com/24843808/195974650-e2d9ef56-ef22-4488-9313-2c9d82486202.png">

maybe, it's a device problem.

could you tell me your environment?

(sorry, too late to reply...)

**Comment by bcdrme** [comment]
Hey @hand-dot ! 

I think you have the problem too but it's just less obvious with macOS's scrollbars. You have to scroll a little bit to the bottom of the page :

![image](https://user-images.githubusercontent.com/54471255/195976339-e31cf2f0-ec8f-41e4-9a9a-4e69d146f689.png)

I'm on Windows using Chrome latest version.

From my understanding, the problem happens because the designer doesn't react properly to parent's size change.
We can get in touch if you want a demonstration.

**Comment by hand-dot** [comment]
@bcdrme 
oh... I understand. 
surely, I could confirm this problem when the scrolling behavior setting changes in system preference.

<img width="1085" alt="CleanShot 2022-10-16 at 15 18 08@2x" src="https://user-images.githubusercontent.com/24843808/196021271-7fd09cf6-0e01-439b-b259-2a01aae56512.png">

I'll fix this problem!

**Comment by hand-dot** [comment]
Hi @bcdrme 

I fixed this problem. 
Please install v 1.0.16.

thanks!

**Comment by bcdrme** [comment]
> Hi @bcdrme
> 
> I fixed this problem. Please install v 1.0.16.
> 
> thanks!

It is a lot better !

There is still a small issue though. Setting no height to the designer's div creates a useless scrollbar :

With height 600px, no scrollbar :
![image](https://user-images.githubusercontent.com/54471255/196655432-4ef14c47-01a3-4f4c-afff-3384b8cdc55e.png)

Without height, one scrollbar for the main page (normal), and one useless scrollbar inside the designer's div :
![image](https://user-images.githubusercontent.com/54471255/196654991-6b179638-9565-40b6-b7f6-aac6f0e93e8e.png)

**Comment by hand-dot** [comment]
@bcdrme 
Sorry, I missed the full-width case...
but now I fixed it.  you can try @pdfme/ui  1.0.17!!

**Comment by bcdrme** [comment]
@hand-dot 
All good ! Good job and thank you ! <3

**Comment by hand-dot** [comment]
@bcdrme 
Thanks report this issue!
